use crate::galaxy::Region;

// Values from https://github.com/klightspeed/EliteDangerousRegionMap
pub const REGIONS: &[Region] = &[
    Region::Unknown,
    Region::GalacticCenter,
    Region::EmpyreonStraits,
    Region::RykersHope,
    Region::OdinsHold,
    Region::NormaArm,
    Region::ArcadianStream,
    Region::Izanami,
    Region::InnerOrionPerseusConflux,
    Region::InnerScutumCentaurusArm,
    Region::NormaExpanse,
    Region::TrojanBelt,
    Region::TheVeils,
    Region::NewtonsVault,
    Region::TheConduit,
    Region::OuterOrionPerseusConflux,
    Region::OrionCygnusArm,
    Region::Temple,
    Region::InnerOrionSpur,
    Region::HawkingsGap,
    Region::DrymansPoint,
    Region::SagittariusCarinaArm,
    Region::MareSomnia,
    Region::Acheron,
    Region::FormorianFrontier,
    Region::HieronymusDelta,
    Region::OuterScutumCentaurusArm,
    Region::OuterArm,
    Region::AquilasHalo,
    Region::ErrantMarches,
    Region::PerseusArm,
    Region::FormidineRift,
    Region::VulcanGate,
    Region::ElysianShore,
    Region::SanguineousRim,
    Region::OuterOrionSpur,
    Region::AchillessAltar,
    Region::Xibalba,
    Region::LysasSong,
    Region::Tenebrae,
    Region::TheAbyss,
    Region::KeplersCrest,
    Region::TheVoid,
];
