use crate::SpawnCondition;
use crate::SpawnCondition::*;
use ed_journals::exobiology::Species;
use ed_journals::exobiology::Species::*;
use ed_journals::galaxy::AtmosphereType::*;
use ed_journals::galaxy::PlanetClass::*;
use ed_journals::galaxy::Region::*;
use ed_journals::galaxy::VolcanismType;
use ed_journals::galaxy::VolcanismType::*;
use ed_journals::galaxy::{StarClass, StarLuminosity};
use ed_journals::materials::Material;

macro_rules! any {
    ($($x:expr),*$(,)?) => {
        SpawnCondition::Any(&[$($x),*])
    };
}

macro_rules! all {
    ($($x:expr),*$(,)?) => {
        SpawnCondition::All(&[$($x),*])
    };
}

pub static SPECIES_SPAWN_CONDITIONS: &[(Species, SpawnCondition<'_>)] = &[
    (
        AleoidaArcus,
        all![
            ThinAtmosphere(CarbonDioxide),
            MinGravity(0.04),
            MaxGravity(0.276),
            MinMeanTemperature(175.0),
            MaxMeanTemperature(180.0),
            MinPressure(0.0164),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            VolcanismType(VolcanismType::None),
        ],
    ),
    (
        AleoidaCoronamus,
        all![
            ThinAtmosphere(CarbonDioxide),
            MinGravity(0.04),
            MaxGravity(0.276),
            MinMeanTemperature(180.0),
            MaxMeanTemperature(190.0),
            MinPressure(0.025),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            VolcanismType(VolcanismType::None),
        ],
    ),
    (
        AleoidaGravis,
        all![
            ThinAtmosphere(CarbonDioxide),
            MinGravity(0.04),
            MaxGravity(0.276),
            MinMeanTemperature(190.0),
            MaxMeanTemperature(196.0),
            MinPressure(0.054),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            VolcanismType(VolcanismType::None)
        ],
    ),
    (
        AleoidaLaminiae,
        all![
            ThinAtmosphere(Ammonia),
            MinGravity(0.04),
            MaxGravity(0.276),
            MinMeanTemperature(152.0),
            MaxMeanTemperature(177.0),
            MaxPressure(0.0135),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            any![
                Region(Acheron),
                Region(DrymansPoint),
                Region(GalacticCenter),
                Region(HawkingsGap),
                Region(InnerOrionPerseusConflux),
                Region(InnerOrionSpur),
                Region(InnerScutumCentaurusArm),
                Region(Izanami),
                Region(MareSomnia),
                Region(OdinsHold),
                Region(OrionCygnusArm),
                Region(OuterOrionSpur),
                Region(SagittariusCarinaArm),
                Region(Temple),
                Region(TheAbyss),
            ],
        ],
    ),
    (
        AleoidaSpica,
        all![
            ThinAtmosphere(Ammonia),
            MinGravity(0.04),
            MaxGravity(0.276),
            MinMeanTemperature(170.0),
            MaxMeanTemperature(177.0),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            // any![
            //     Region(Region::OuterArm),
            //     Region(Region::OuterOrionSpur),
            //     Region(Region::OuterScutumCentaurusArm),
            //     Region(Region::OuterOrionPerseusConflux),
            //     Region(Region::PerseusArm),
            //     Region(Region::InnerOrionPerseusConflux),
            //     Region(Region::InnerScutumCentaurusArm),
            //     Region(Region::OuterScutumCentaurusArm),
            // ],
        ],
    ),
    (
        AmphoraPlant,
        all![
            ParentStarClass(StarClass::A),
            NoAtmosphere,
            PlanetClass(MetalRichBody),
            any![
                SystemContainsPlanetClass(EarthlikeBody),
                SystemContainsPlanetClass(AmmoniaWorld),
                SystemContainsPlanetClass(GasGiantWithWaterBasedLife,),
                SystemContainsPlanetClass(GasGiantWithAmmoniaBasedLife,),
                SystemContainsPlanetClass(WaterGiant),
            ],
        ],
    ),
    (
        AnemonePrasinumBioluminescent,
        all![
            NoAtmosphere,
            MinGravity(0.036),
            MinMeanTemperature(110.0),
            MaxMeanTemperature(3050.0),
            any![
                VolcanismType(VolcanismType::CarbonDioxideGeysers),
                VolcanismType(VolcanismType::None),
            ],
            any![
                PlanetClass(MetalRichBody),
                PlanetClass(RockyBody),
                PlanetClass(HighMetalContentBody),
            ],
            any![
                PrimaryStarClass(StarClass::O),
                PrimaryStarClass(StarClass::AeBe),
            ],
        ],
    ),
    (
        AnemonePuniceum,
        all![
            NoAtmosphere,
            MinGravity(0.17),
            MaxGravity(2.52),
            MinMeanTemperature(65.0),
            MaxMeanTemperature(800.0),
            any![
                VolcanismType(VolcanismType::None),
                VolcanismType(VolcanismType::CarbonDioxideGeysers),
            ],
            any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
            ParentStarClass(StarClass::O),
            Region(ArcadianStream),
            // TODO: 'regions': ['anemone-a'] ?? Which region is this?
        ],
    ),
    (
        AnemoneRoseumBioluminescent,
        all![
            NoAtmosphere,
            MinGravity(0.036),
            MaxGravity(4.61),
            MinMeanTemperature(400.0),
            AnyVolcanism,
            any![
                PlanetClass(MetalRichBody),
                PlanetClass(HighMetalContentBody),
            ],
            ParentStarClass(StarClass::B),
            any![
                ParentStarLuminosity(StarLuminosity::I),
                ParentStarLuminosity(StarLuminosity::II),
                ParentStarLuminosity(StarLuminosity::III),
            ],
        ],
    ),
    (
        AnemoneRoseum,
        all![
            NoAtmosphere,
            MinGravity(0.045),
            MaxGravity(0.37),
            MinMeanTemperature(200.0),
            MaxMeanTemperature(440.0),
            any![
                VolcanismType(VolcanismType::SilicateMagma),
                VolcanismType(VolcanismType::RockyMagma),
                VolcanismType(VolcanismType::MetallicMagma),
            ],
            PlanetClass(RockyBody),
            all![
                ParentStarClass(StarClass::B),
                any![
                    ParentStarLuminosity(StarLuminosity::I),
                    ParentStarLuminosity(StarLuminosity::II),
                    ParentStarLuminosity(StarLuminosity::III),
                    ParentStarLuminosity(StarLuminosity::IV),
                ],
            ],
            // TODO: 'regions': ['anemone-a'] ?? Which region is this?
        ],
    ),
    (
        AnemoneBlatteumBioluminescent,
        all![
            NoAtmosphere,
            MinMeanTemperature(220.0),
            AnyVolcanism,
            any![
                PlanetClass(MetalRichBody),
                PlanetClass(HighMetalContentBody),
            ],
            all![
                ParentStarClass(StarClass::B),
                any![
                    ParentStarLuminosity(StarLuminosity::IV),
                    ParentStarLuminosity(StarLuminosity::V),
                ],
            ],
            // TODO: 'regions': ['anemone-a'] ?? Which region is this?
        ],
    ),
    (
        AnemoneLuteolum,
        all![
            NoAtmosphere,
            MinGravity(0.044),
            MaxGravity(1.28),
            MinMeanTemperature(200.0),
            MaxMeanTemperature(400.0),
            any![
                VolcanismType(VolcanismType::MetallicMagma),
                VolcanismType(VolcanismType::SilicateMagma),
                VolcanismType(VolcanismType::RockyMagma),
                VolcanismType(VolcanismType::WaterMagma),
            ],
            PlanetClass(RockyBody),
            ParentStarClass(StarClass::B),
            any![
                ParentStarLuminosity(StarLuminosity::IV),
                ParentStarLuminosity(StarLuminosity::V),
            ],
            // TODO: 'regions': ['anemone-a'] ?? Which region is this?
        ],
    ),
    (
        AnemoneRubeumBioluminescent,
        all![
            NoAtmosphere,
            MinGravity(0.036),
            MaxGravity(4.61),
            MinMeanTemperature(160.0),
            MaxMeanTemperature(1800.0),
            AnyVolcanism,
            any![
                PlanetClass(MetalRichBody),
                PlanetClass(HighMetalContentBody),
            ],
            any![
                all![
                    ParentStarClass(StarClass::B),
                    ParentStarLuminosity(StarLuminosity::VI),
                ],
                all![
                    ParentStarClass(StarClass::A),
                    any![
                        ParentStarLuminosity(StarLuminosity::I),
                        ParentStarLuminosity(StarLuminosity::II),
                        ParentStarLuminosity(StarLuminosity::III),
                    ],
                ],
                ParentStarClass(StarClass::N),
            ],
        ],
    ),
    (
        AnemoneCroceum,
        all![
            NoAtmosphere,
            MinGravity(0.047),
            MaxGravity(0.37),
            MinMeanTemperature(200.0),
            MaxMeanTemperature(440.0),
            any![
                VolcanismType(VolcanismType::SilicateMagma),
                VolcanismType(VolcanismType::RockyMagma),
                VolcanismType(VolcanismType::MetallicMagma)
            ],
            PlanetClass(RockyBody),
            any![
                all![
                    ParentStarClass(StarClass::B),
                    any![
                        ParentStarLuminosity(StarLuminosity::V),
                        ParentStarLuminosity(StarLuminosity::IV),
                    ],
                ],
                all![
                    ParentStarClass(StarClass::A),
                    ParentStarLuminosity(StarLuminosity::III),
                ],
            ],
            // TODO: regions': ['anemone-a'] ?? Which region is this?
        ],
    ),
    (BarkMound, all![NoAtmosphere, WithinNebulaRange(150.0),]),
    (BacteriumNebulus, ThinAtmosphere(Helium)),
    (
        BacteriumAcies,
        any![ThinAtmosphere(Neon), ThinAtmosphere(NeonRich),],
    ),
    (
        BacteriumOmentum,
        all![
            any![
                ThinAtmosphere(Neon),
                ThinAtmosphere(NeonRich),
                ThinAtmosphere(Methane),
                ThinAtmosphere(Argon),
                ThinAtmosphere(ArgonRich),
                ThinAtmosphere(WaterRich),
                ThinAtmosphere(Helium),
                ThinAtmosphere(Nitrogen),
            ],
            any![
                VolcanismType(VolcanismType::NitrogenMagma),
                VolcanismType(VolcanismType::NitrogenGeysers),
                VolcanismType(VolcanismType::AmmoniaMagma),
                VolcanismType(VolcanismType::AmmoniaGeysers),
            ],
        ],
    ),
    (
        BacteriumScopulum,
        all![
            any![
                ThinAtmosphere(Argon),
                ThinAtmosphere(CarbonDioxide),
                ThinAtmosphere(CarbonDioxideRich),
                ThinAtmosphere(Helium),
                ThinAtmosphere(Methane),
                ThinAtmosphere(Neon),
                ThinAtmosphere(NeonRich),
                ThinAtmosphere(Nitrogen),
                ThinAtmosphere(Oxygen),
            ],
            any![
                VolcanismType(CarbonDioxideGeysers),
                VolcanismType(MethaneGeysers),
                VolcanismType(MethaneMagma),
            ],
        ],
    ),
    (
        BacteriumVerrata,
        all![
            any![
                PlanetClass(IcyBody),
                PlanetClass(RockyBody),
                PlanetClass(RockyIceBody),
            ],
            any![VolcanismType(WaterMagma), VolcanismType(WaterGeysers),],
            any![
                all![
                    any![ThinAtmosphere(Argon), ThinAtmosphere(ArgonRich),],
                    MinGravity(0.169),
                    MaxGravity(0.36),
                    MinMeanTemperature(59.9),
                    MaxMeanTemperature(145.0),
                ],
                all![
                    ThinAtmosphere(Ammonia),
                    MinGravity(0.03),
                    MaxGravity(0.09),
                    MinMeanTemperature(160.0),
                    MaxMeanTemperature(176.0),
                ],
                all![
                    ThinAtmosphere(Helium),
                    MinGravity(0.49),
                    MaxGravity(0.51),
                    MinMeanTemperature(20.0),
                    MaxMeanTemperature(21.0),
                    MinPressure(0.068),
                ],
                all![
                    ThinAtmosphere(Neon),
                    MinGravity(0.28),
                    MaxGravity(0.61),
                    MinMeanTemperature(20.0),
                    MaxMeanTemperature(51.0),
                    MaxPressure(0.0076),
                ],
                all![
                    ThinAtmosphere(NeonRich),
                    MinGravity(0.42),
                    MaxGravity(0.61),
                    MinMeanTemperature(20.0),
                    MaxMeanTemperature(65.0),
                    MinPressure(0.006),
                ],
                all![
                    any![
                        ThinAtmosphere(CarbonDioxide),
                        ThinAtmosphere(CarbonDioxideRich),
                    ],
                    MinGravity(0.25),
                    MaxGravity(0.39),
                    MinMeanTemperature(167.0),
                    MaxMeanTemperature(235.0),
                ],
                all![
                    ThinAtmosphere(Methane),
                    MinGravity(0.08),
                    MaxGravity(0.1),
                    MinMeanTemperature(95.0),
                    MaxMeanTemperature(100.0),
                ],
                all![
                    ThinAtmosphere(Nitrogen),
                    MinGravity(0.21),
                    MaxGravity(0.25),
                    MinMeanTemperature(59.0),
                    MaxMeanTemperature(80.0),
                ],
                all![
                    ThinAtmosphere(Oxygen),
                    MinGravity(0.24),
                    MaxGravity(0.38),
                    MinMeanTemperature(155.0),
                    MaxMeanTemperature(220.0),
                    MinPressure(0.019),
                ],
                all![
                    ThinAtmosphere(Water),
                    MinGravity(0.04),
                    MaxGravity(0.054),
                    MinMeanTemperature(405.0),
                    MaxMeanTemperature(445.0),
                    MinPressure(0.061),
                ],
            ],
        ],
    ),
    (
        BacteriumBullaris,
        any![ThinAtmosphere(Methane), ThinAtmosphere(MethaneRich),],
    ),
    (BacteriumAlcyoneum, ThinAtmosphere(Ammonia)),
    (
        BacteriumVesicula,
        any![ThinAtmosphere(Argon), ThinAtmosphere(ArgonRich),],
    ),
    (
        BacteriumCerbrus,
        all![
            MinMeanTemperature(132.0),
            MaxMeanTemperature(500.0),
            any![ThinAtmosphere(SulfurDioxide), ThinAtmosphere(Water),],
            any![
                all![MinGravity(0.04), MaxGravity(0.06),],
                all![MinGravity(0.23), MaxGravity(0.6),],
            ],
        ],
    ),
    (
        BacteriumAurasus,
        any![
            ThinAtmosphere(CarbonDioxide),
            ThinAtmosphere(CarbonDioxideRich),
        ],
    ),
    (BacteriumInformem, ThinAtmosphere(Nitrogen)),
    (BacteriumVolu, ThinAtmosphere(Oxygen)),
    (
        BacteriumTela,
        any![
            all![
                ThinAtmosphere(SulfurDioxide),
                MinGravity(0.18),
                MaxGravity(0.61),
                MinMeanTemperature(153.0),
                MaxMeanTemperature(500.0),
            ],
            all![
                any![
                    ThinAtmosphere(CarbonDioxide),
                    ThinAtmosphere(CarbonDioxideRich),
                ],
                MinGravity(0.45),
                MaxGravity(0.61),
                MinMeanTemperature(300.0),
                MaxMeanTemperature(500.0),
                MinPressure(0.006),
                any![
                    VolcanismType(VolcanismType::None),
                    VolcanismType(SilicateVapourGeysers),
                ],
            ],
            all![
                ThinAtmosphere(Water),
                any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
                MinGravity(0.04),
                MaxGravity(0.063),
                MinMeanTemperature(395.0),
                MaxMeanTemperature(450.0),
                any![
                    VolcanismType(VolcanismType::None),
                    VolcanismType(WaterMagma),
                ],
            ],
            all![
                ThinAtmosphere(WaterRich),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
                MinGravity(0.32),
                MaxGravity(0.44),
                MinMeanTemperature(220.0),
                MaxMeanTemperature(330.0),
                MinPressure(0.01),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(Argon),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
                MinGravity(0.045),
                MaxGravity(0.28),
                MinMeanTemperature(50.0),
                MaxMeanTemperature(170.0),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(ArgonRich),
                MinGravity(0.24),
                MaxGravity(0.45),
                MinMeanTemperature(50.0),
                MaxMeanTemperature(150.0),
                MaxPressure(0.05),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(Ammonia),
                MinGravity(0.03),
                MaxGravity(0.09),
                MinMeanTemperature(160.0),
                MaxMeanTemperature(177.0),
                MinPressure(0.002),
                MaxPressure(0.02),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(Helium),
                PlanetClass(IcyBody),
                MinGravity(0.49),
                MaxGravity(0.53),
                MinMeanTemperature(20.0),
                MaxMeanTemperature(21.0),
                MinPressure(0.067),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(Methane),
                any![
                    PlanetClass(IcyBody),
                    PlanetClass(RockyBody),
                    PlanetClass(HighMetalContentBody)
                ],
                MinGravity(0.026),
                MaxGravity(0.126),
                MinMeanTemperature(77.0),
                MaxMeanTemperature(109.0),
                MinPressure(0.012),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(Neon),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
                MinGravity(0.27),
                MaxGravity(0.61),
                MinMeanTemperature(20.0),
                MaxMeanTemperature(61.0),
                MinPressure(0.001),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(NeonRich),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
                MinGravity(0.27),
                MaxGravity(0.61),
                MinMeanTemperature(20.0),
                MaxMeanTemperature(95.0),
                MinPressure(0.002),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(Nitrogen),
                MinGravity(0.21),
                MaxGravity(0.35),
                MinMeanTemperature(55.0),
                MaxMeanTemperature(80.0),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(Oxygen),
                MinGravity(0.23),
                MaxGravity(0.52),
                MinMeanTemperature(150.0),
                MaxMeanTemperature(240.0),
                MinPressure(0.017),
                AnyVolcanism,
            ],
            all![
                ThinAtmosphere(SulfurDioxide),
                any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
                MinGravity(0.18),
                MaxGravity(0.61),
                MinMeanTemperature(149.0),
                MaxMeanTemperature(500.0),
                MinPressure(0.001),
                VolcanismType(VolcanismType::None),
            ],
        ],
    ),
    (BrainTreeAureum, all![NoAtmosphere, AnyVolcanism,]),
    (BrainTreeOstrinum, all![NoAtmosphere, AnyVolcanism,]),
    (BrainTreePuniceum, all![NoAtmosphere, AnyVolcanism,]),
    (BrainTreeLindigoticum, all![NoAtmosphere, AnyVolcanism,]),
    (BrainTreeGypseeum, all![NoAtmosphere, AnyVolcanism,]),
    (BrainTreeLividum, all![NoAtmosphere, AnyVolcanism,]),
    (BrainTreeViride, all![NoAtmosphere, AnyVolcanism,]),
    (BrainTreeRoseum, all![NoAtmosphere, AnyVolcanism,]),
    (
        CactoidaLapis,
        all![
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            any![
                Region(InnerOrionSpur),
                Region(InnerScutumCentaurusArm),
                Region(GalacticCenter),
                Region(HawkingsGap),
                Region(MareSomnia),
                Region(DrymansPoint),
                Region(SagittariusCarinaArm),
                Region(OdinsHold),
                Region(TheAbyss),
                Region(Acheron),
            ],
            MaxGravity(0.28),
            MinMeanTemperature(160.0),
            MaxMeanTemperature(180.0),
            MaxPressure(0.014),
            ThinAtmosphere(Ammonia),
        ],
    ),
    (
        CactoidaPullulanta,
        all![
            any![
                PlanetClass(IcyBody),
                PlanetClass(RockyBody),
                PlanetClass(HighMetalContentBody),
            ],
            ThinAtmosphere(CarbonDioxide),
            MaxGravity(0.27),
            MinMeanTemperature(180.0),
            MaxMeanTemperature(196.0),
            MinPressure(0.025),
        ],
    ),
    (
        CactoidaCortexum,
        all![
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Ammonia),],
            MaxGravity(0.276),
            MinMeanTemperature(180.0),
            MaxMeanTemperature(196.0),
            MinPressure(0.025),
        ],
    ),
    (
        CactoidaVermis,
        all![
            MaxGravity(0.276),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            ThinAtmosphere(Water),
        ],
    ),
    (
        CactoidaPeperatis,
        all![
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            any![
                Region(NormaExpanse),
                Region(TheVoid),
                Region(GalacticCenter),
                Region(TrojanBelt),
                Region(InnerScutumCentaurusArm),
                Region(OuterScutumCentaurusArm),
                Region(OdinsHold),
                Region(TheVeils),
                Region(AquilasHalo),
                Region(HieronymusDelta),
                Region(FormorianFrontier),
            ],
            MaxGravity(0.28),
            MinMeanTemperature(160.0),
            MaxMeanTemperature(180.0),
            ThinAtmosphere(Ammonia),
        ],
    ),
    (
        ClypeusSpeculumi,
        all![
            MaxGravity(0.276),
            MinMeanTemperature(190.0),
            any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Water),],
            MinDistanceFromParentSun(5.0),
        ],
    ),
    (
        ClypeusLacrimam,
        all![
            MaxGravity(0.276),
            MinMeanTemperature(190.0),
            any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Water),],
        ],
    ),
    (
        ClypeusMargaritus,
        all![
            MaxGravity(0.276),
            MinMeanTemperature(190.0),
            any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Water),],
        ],
    ),
    (
        ConchaRenibus,
        any![
            all![
                MaxGravity(0.276),
                any![
                    ThinAtmosphere(CarbonDioxide),
                    ThinAtmosphere(CarbonDioxideRich)
                ],
                MinMeanTemperature(180.0),
                MaxMeanTemperature(195.0),
            ],
            all![
                MaxGravity(0.276),
                any![ThinAtmosphere(Water), ThinAtmosphere(WaterRich),],
            ],
        ],
    ),
    (
        ConchaAureolas,
        all![
            ThinAtmosphere(Ammonia),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MinGravity(0.039),
            MaxGravity(0.276),
            MinMeanTemperature(152.0),
            MaxMeanTemperature(177.0),
            MaxPressure(0.013),
        ],
    ),
    (
        ConchaLabiata,
        all![
            ThinAtmosphere(CarbonDioxide),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MinGravity(0.039),
            MaxGravity(0.276),
            MinMeanTemperature(150.0),
            MaxMeanTemperature(195.0),
            MaxMeanTemperature(195.0),
        ],
    ),
    (
        ConchaBiconcavis,
        all![MaxGravity(0.276), ThinAtmosphere(Nitrogen),],
    ),
    (
        CrystallineShards,
        all![
            NoAtmosphere,
            any![
                ParentStarClass(StarClass::A),
                ParentStarClass(StarClass::F),
                ParentStarClass(StarClass::G),
                ParentStarClass(StarClass::K),
                ParentStarClass(StarClass::M),
                ParentStarClass(StarClass::S),
            ],
            MinMeanTemperature(0.0),
            MaxMeanTemperature(273.0),
            any![
                SystemContainsPlanetClass(EarthlikeBody),
                SystemContainsPlanetClass(AmmoniaWorld),
                SystemContainsPlanetClass(GasGiantWithWaterBasedLife,),
                SystemContainsPlanetClass(GasGiantWithAmmoniaBasedLife,),
                SystemContainsPlanetClass(WaterGiant),
            ],
            MinDistanceFromParentSun(24.0),
        ],
    ),
    (
        ElectricaePluma,
        all![
            any![
                ThinAtmosphere(Helium),
                ThinAtmosphere(Neon),
                ThinAtmosphere(Argon),
            ],
            PlanetClass(IcyBody),
            ParentStarClass(StarClass::A),
            any![
                MinOrEqualParentStarLuminosity(StarLuminosity::V),
                ParentStarClass(StarClass::N),
            ],
            MaxGravity(0.276),
        ],
    ),
    (
        ElectricaeRadialem,
        all![
            any![
                ThinAtmosphere(Helium),
                ThinAtmosphere(Neon),
                ThinAtmosphere(Argon),
            ],
            PlanetClass(IcyBody),
            WithinNebulaRange(150.0),
            MaxGravity(0.276),
        ],
    ),
    (
        FonticuluaCampestris,
        all![
            ThinAtmosphere(Argon),
            any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
            MaxGravity(0.276),
            MinMeanTemperature(50.0),
            MaxMeanTemperature(150.0),
        ],
    ),
    (
        FonticuluaSegmentatus,
        all![
            any![ThinAtmosphere(Neon), ThinAtmosphere(NeonRich)],
            any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        FonticuluaDigitos,
        all![
            any![ThinAtmosphere(Methane), ThinAtmosphere(MethaneRich),],
            any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        FonticuluaUpupam,
        all![
            ThinAtmosphere(ArgonRich),
            any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        FonticuluaLapida,
        all![
            ThinAtmosphere(Nitrogen),
            any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        FonticuluaFluctus,
        all![
            ThinAtmosphere(Oxygen),
            any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        FrutexaAcus,
        all![
            any![
                Region(Temple),
                Region(GalacticCenter),
                Region(Izanami),
                Region(InnerOrionSpur),
                Region(OuterOrionSpur),
                Region(OrionCygnusArm),
                Region(OdinsHold),
                Region(InnerOrionPerseusConflux),
            ],
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MinGravity(0.04),
            MaxGravity(0.276),
            MinMeanTemperature(147.0),
            MaxMeanTemperature(195.0),
            MinPressure(0.003),
        ],
    ),
    (
        FrutexaCollum,
        all![
            ThinAtmosphere(SulfurDioxide),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
        ],
    ),
    (
        FrutexaFera,
        all![
            any![
                Region(GalacticCenter),
                Region(EmpyreonStraits),
                Region(OuterArm),
                Region(FormidineRift),
                Region(ArcadianStream),
                Region(TheConduit),
                Region(NewtonsVault),
                Region(NormaArm),
                Region(KeplersCrest),
                Region(Xibalba),
            ],
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MinGravity(0.04),
            MaxGravity(0.25),
            MinMeanTemperature(145.0),
            MaxMeanTemperature(200.0),
            MinPressure(0.003),
        ],
    ),
    (
        FrutexaFlabellum,
        all![
            ThinAtmosphere(Ammonia),
            PlanetClass(RockyBody),
            MaxPressure(0.014),
            MinGravity(0.04),
            MaxGravity(0.28),
            MinMeanTemperature(155.0),
            MaxMeanTemperature(177.0),
        ],
    ),
    (
        FrutexaFlammasis,
        all![
            any![
                Region(GalacticCenter),
                Region(NormaExpanse),
                Region(InnerScutumCentaurusArm),
                Region(OuterScutumCentaurusArm),
                Region(AquilasHalo),
                Region(OdinsHold),
                Region(TheVeils),
                Region(TheVoid),
                Region(HieronymusDelta),
                Region(FormorianFrontier),
                Region(TrojanBelt),
            ],
            PlanetClass(RockyBody),
            ThinAtmosphere(Ammonia),
            MaxPressure(0.0134),
            MinGravity(0.04),
            MaxGravity(0.28),
            MinMeanTemperature(152.0),
            MaxMeanTemperature(177.0),
        ],
    ),
    (
        FrutexaMetallicum,
        all![
            any![
                all![ThinAtmosphere(CarbonDioxide), MaxMeanTemperature(195.0),],
                ThinAtmosphere(Ammonia)
            ],
            PlanetClass(HighMetalContentBody),
            MaxGravity(0.276),
        ],
    ),
    (
        FrutexaSponsae,
        all![
            ThinAtmosphere(Water),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
        ],
    ),
    (
        FumerolaAquatis,
        all![
            AnyThinAtmosphere,
            GeologicalSignalsPresent,
            any![VolcanismType(WaterMagma), VolcanismType(WaterGeysers),],
            MaxGravity(0.276),
        ],
    ),
    (
        FumerolaCarbosis,
        all![
            AnyThinAtmosphere,
            GeologicalSignalsPresent,
            any![
                VolcanismType(CarbonDioxideGeysers),
                VolcanismType(MethaneMagma),
                VolcanismType(MethaneGeysers),
            ],
            MaxGravity(0.276),
        ],
    ),
    (
        FumerolaExtremus,
        all![
            AnyThinAtmosphere,
            GeologicalSignalsPresent,
            any![
                MaterialPresence(Material::Iron),
                VolcanismType(CarbonDioxideGeysers),
                VolcanismType(MethaneMagma),
                VolcanismType(MethaneGeysers),
            ],
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        FumerolaNitris,
        all![
            AnyThinAtmosphere,
            GeologicalSignalsPresent,
            any![
                VolcanismType(NitrogenMagma),
                VolcanismType(NitrogenGeysers),
                VolcanismType(AmmoniaMagma),
                VolcanismType(AmmoniaGeysers),
            ],
            MaxGravity(0.276),
        ],
    ),
    (
        FungoidaBullarum,
        all![
            any![
                ThinAtmosphere(Argon),
                ThinAtmosphere(ArgonRich),
                ThinAtmosphere(Nitrogen),
            ],
            any![
                PlanetClass(RockyIceBody),
                PlanetClass(RockyBody),
                PlanetClass(HighMetalContentBody),
            ],
            MinMeanTemperature(50.0),
            MaxMeanTemperature(135.0),
            MaxPressure(0.1),
            MaxGravity(0.276),
        ],
    ),
    (
        FungoidaGelata,
        all![
            any![
                PlanetClass(RockyBody),
                PlanetClass(RockyIceBody),
                PlanetClass(HighMetalContentBody),
            ],
            MinPressure(0.0026),
            MaxGravity(0.28),
            any![
                all![
                    ThinAtmosphere(Water),
                    MinMeanTemperature(392.0),
                    MaxMeanTemperature(452.0),
                ],
                all![
                    ThinAtmosphere(Ammonia),
                    MinMeanTemperature(160.0),
                    MaxMeanTemperature(177.0),
                ],
                all![
                    ThinAtmosphere(CarbonDioxide),
                    MinMeanTemperature(180.0),
                    MaxMeanTemperature(197.0),
                ],
                all![
                    ThinAtmosphere(Methane),
                    MinMeanTemperature(79.0),
                    MaxMeanTemperature(107.0),
                ],
            ],
        ],
    ),
    (
        FungoidaSetisis,
        all![
            any![ThinAtmosphere(Ammonia), ThinAtmosphere(Methane),],
            MaxGravity(0.276),
        ],
    ),
    (
        FungoidaStabitis,
        all![
            any![
                ThinAtmosphere(Water),
                all![
                    ThinAtmosphere(CarbonDioxide),
                    MinMeanTemperature(180.0),
                    MaxMeanTemperature(195.0),
                ],
            ],
            MaxGravity(0.276),
        ],
    ),
    (
        OsseusCornibus,
        all![
            ThinAtmosphere(CarbonDioxide),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MaxGravity(0.276),
            MinMeanTemperature(180.0),
            MaxMeanTemperature(195.0),
        ],
    ),
    (
        OsseusDiscus,
        all![
            ThinAtmosphere(Water),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        OsseusFractus,
        all![
            ThinAtmosphere(CarbonDioxide),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MaxGravity(0.276),
            MinMeanTemperature(180.0),
            MaxMeanTemperature(195.0),
        ],
    ),
    (
        OsseusPellebantus,
        all![
            ThinAtmosphere(CarbonDioxide),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MaxGravity(0.276),
            MinMeanTemperature(180.0),
            MaxMeanTemperature(195.0),
        ],
    ),
    (
        OsseusPumice,
        all![
            any![
                ThinAtmosphere(Argon),
                ThinAtmosphere(ArgonRich),
                ThinAtmosphere(Methane),
                ThinAtmosphere(Nitrogen),
            ],
            any![
                PlanetClass(RockyIceBody),
                PlanetClass(HighMetalContentBody),
                PlanetClass(RockyBody),
            ],
            any![
                PlanetClass(RockyBody),
                PlanetClass(HighMetalContentBody),
                PlanetClass(RockyIceBody),
            ],
            MaxGravity(0.276),
            MinMeanTemperature(43.0),
            MaxMeanTemperature(135.0),
        ],
    ),
    (
        OsseusSpiralis,
        all![
            ThinAtmosphere(Ammonia),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MaxGravity(0.276)
        ],
    ),
    (RadicoidaUnica, Special),
    (
        ReceptaConditivus,
        all![
            ThinAtmosphere(SulfurDioxide),
            any![PlanetClass(IcyBody), PlanetClass(RockyIceBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        ReceptaDeltahedronix,
        all![
            ThinAtmosphere(SulfurDioxide),
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            MaxGravity(0.276),
        ],
    ),
    (
        ReceptaUmbrux,
        all![ThinAtmosphere(SulfurDioxide), MaxGravity(0.276),],
    ),
    (
        SinuousTubersAlbidum,
        all![NoAtmosphere, PlanetClass(RockyBody),],
    ),
    (
        SinuousTubersBlatteum,
        all![
            NoAtmosphere,
            any![
                PlanetClass(MetalRichBody),
                PlanetClass(HighMetalContentBody),
            ],
        ],
    ),
    (
        SinuousTubersCaeruleum,
        all![NoAtmosphere, PlanetClass(RockyBody),],
    ),
    (
        SinuousTubersLindigoticum,
        all![NoAtmosphere, PlanetClass(RockyBody),],
    ),
    (
        SinuousTubersPrasinum,
        all![
            NoAtmosphere,
            any![
                PlanetClass(MetalRichBody),
                PlanetClass(HighMetalContentBody),
            ],
        ],
    ),
    (
        SinuousTubersRoseum,
        all![NoAtmosphere, VolcanismType(SilicateMagma),],
    ),
    (
        SinuousTubersViolaceum,
        all![
            NoAtmosphere,
            any![
                PlanetClass(MetalRichBody),
                PlanetClass(HighMetalContentBody),
            ],
        ],
    ),
    (
        SinuousTubersViride,
        all![
            NoAtmosphere,
            any![
                PlanetClass(MetalRichBody),
                PlanetClass(HighMetalContentBody),
            ],
        ],
    ),
    (
        StratumAraneamus,
        all![
            ThinAtmosphere(SulfurDioxide),
            PlanetClass(RockyBody),
            MinMeanTemperature(165.0),
            MaxMeanTemperature(375.0),
            MinGravity(0.26),
            MaxGravity(0.56),
        ],
    ),
    (
        StratumCucumisis,
        all![
            any![
                ThinAtmosphere(SulfurDioxide),
                ThinAtmosphere(CarbonDioxide),
                ThinAtmosphere(CarbonDioxideRich),
            ],
            PlanetClass(RockyBody),
            MinMeanTemperature(190.0),
            MaxMeanTemperature(375.0),
            MinGravity(0.04),
            MaxGravity(0.6),
        ],
    ),
    (
        StratumExcutitus,
        all![
            any![
                ThinAtmosphere(Oxygen),
                ThinAtmosphere(SulfurDioxide),
                ThinAtmosphere(CarbonDioxide),
            ],
            any![
                Region(GalacticCenter),
                Region(OdinsHold),
                Region(InnerOrionSpur),
                Region(OuterOrionSpur),
                Region(OrionCygnusArm),
                Region(Izanami),
                Region(Temple),
                Region(InnerOrionPerseusConflux),
            ],
            PlanetClass(RockyBody),
            MinGravity(0.04),
            MaxGravity(0.48),
            MinMeanTemperature(165.0),
            MaxMeanTemperature(190.0),
        ],
    ),
    (
        StratumFrigus,
        all![
            any![
                ThinAtmosphere(SulfurDioxide),
                ThinAtmosphere(CarbonDioxide),
                ThinAtmosphere(CarbonDioxideRich),
            ],
            PlanetClass(RockyBody),
            MinMeanTemperature(190.0),
            MinGravity(0.04),
            MaxGravity(0.551),
        ],
    ),
    (
        StratumLaminamus,
        all![
            any![
                Region(InnerOrionSpur),
                Region(OuterOrionSpur),
                Region(Izanami),
                Region(GalacticCenter),
                Region(OrionCygnusArm),
                Region(OdinsHold),
                Region(InnerOrionPerseusConflux),
                Region(Temple),
            ],
            ThinAtmosphere(Ammonia),
            PlanetClass(RockyBody),
            MaxPressure(0.0134),
            MinGravity(0.04),
            MaxGravity(0.35),
            MinMeanTemperature(165.0),
            MaxMeanTemperature(177.0),
        ],
    ),
    (
        StratumLimaxus,
        all![
            any![ThinAtmosphere(SulfurDioxide), ThinAtmosphere(CarbonDioxide),],
            any![
                Region(NormaExpanse),
                Region(InnerScutumCentaurusArm),
                Region(OuterScutumCentaurusArm),
                Region(FormorianFrontier),
                Region(TheVoid),
                Region(AquilasHalo),
                Region(HieronymusDelta),
                Region(TheVeils),
                Region(TrojanBelt),
            ],
            PlanetClass(RockyBody),
            MinMeanTemperature(165.0),
            MaxMeanTemperature(190.0),
            MinGravity(0.04),
            MaxGravity(0.5),
        ],
    ),
    (
        StratumPaleas,
        any![
            all![
                ThinAtmosphere(Ammonia),
                MinMeanTemperature(165.0),
                MaxMeanTemperature(177.0),
                // any![
                //     Region(Region::InnerOrionSpur),
                //     Region(Region::ArcadianStream),
                //     Region(Region::NormaExpanse),
                //     Region(Region::OdinsHold),
                //     Region(Region::InnerScutumCentaurusArm),
                //     Region(Region::OuterOrionPerseusConflux),
                //     Region(Region::TrojanBelt),
                //     Region(Region::ElysianShore),
                //     Region(Region::AquilasHalo),
                //     Region(Region::ErrantMarches),
                //     Region(Region::VulcanGate),
                //     Region(Region::Xibalba),
                //     Region(Region::DrymansPoint),
                //     Region(Region::SagittariusCarinaArm),
                // ],
            ],
            all![
                ThinAtmosphere(CarbonDioxide),
                MinGravity(0.04),
                MaxGravity(0.27),
                MinMeanTemperature(165.0),
                MaxMeanTemperature(196.0),
            ],
            all![
                ThinAtmosphere(CarbonDioxide),
                MinGravity(0.27),
                MinMeanTemperature(165.0),
                MaxMeanTemperature(400.0),
            ],
            all![
                ThinAtmosphere(CarbonDioxideRich),
                MinMeanTemperature(170.0),
                MaxMeanTemperature(255.0),
            ],
            all![
                ThinAtmosphere(Oxygen),
                MinMeanTemperature(165.0),
                MaxMeanTemperature(250.0),
                MinGravity(0.04),
                MinGravity(0.056),
            ],
            all![
                ThinAtmosphere(Water),
                MinMeanTemperature(397.0),
                MaxMeanTemperature(450.0),
                MinGravity(0.04),
                MaxGravity(0.056),
                MinPressure(0.055),
            ],
            ThinAtmosphere(Nitrogen),
        ],
    ),
    (
        StratumTectonicas,
        all![
            AnyThinAtmosphere,
            PlanetClass(HighMetalContentBody),
            MinMeanTemperature(165.0),
        ],
    ),
    (
        TubusCavas,
        all![
            ThinAtmosphere(CarbonDioxide),
            any![
                Region(InnerScutumCentaurusArm),
                Region(OuterScutumCentaurusArm),
                Region(FormorianFrontier),
                Region(GalacticCenter),
                Region(NormaExpanse),
                Region(OdinsHold),
                Region(TheVoid),
                Region(AquilasHalo),
                Region(HieronymusDelta),
                Region(TheVeils),
                Region(TrojanBelt),
            ],
            PlanetClass(RockyBody),
            MinGravity(0.04),
            MaxGravity(0.15),
            MinMeanTemperature(160.0),
            MaxMeanTemperature(190.0),
        ],
    ),
    (
        TubusCompagibus,
        all![
            any![
                Region(GalacticCenter),
                Region(OdinsHold),
                Region(InnerScutumCentaurusArm),
                Region(InnerOrionSpur),
                Region(HawkingsGap),
                Region(TheAbyss),
                Region(Acheron),
                Region(MareSomnia),
                Region(DrymansPoint),
                Region(SagittariusCarinaArm),
            ],
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MinGravity(0.04),
            MaxGravity(0.152),
            MinMeanTemperature(160.0),
            MaxMeanTemperature(195.0),
        ],
    ),
    (
        TubusConifer,
        all![
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MinGravity(0.041),
            MaxGravity(0.15),
            MinMeanTemperature(160.0),
            MaxMeanTemperature(190.0),
            VolcanismType(VolcanismType::None),
            MinPressure(0.003),
        ],
    ),
    (
        TubusRosarium,
        all![
            ThinAtmosphere(Ammonia),
            PlanetClass(RockyBody),
            MaxGravity(0.15),
            MinMeanTemperature(160.0),
        ],
    ),
    (
        TubusSororibus,
        all![
            any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Ammonia),],
            PlanetClass(HighMetalContentBody),
            MaxGravity(0.15),
            MinMeanTemperature(160.0),
            MaxMeanTemperature(190.0),
        ],
    ),
    (
        TussockAlbata,
        all![
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
            MinMeanTemperature(175.0),
            MaxMeanTemperature(180.0),
        ],
    ),
    (
        TussockCapillum,
        all![
            any![PlanetClass(RockyBody), PlanetClass(RockyIceBody),],
            any![ThinAtmosphere(Argon), ThinAtmosphere(Methane),],
            MaxGravity(0.276),
            MinMeanTemperature(80.0),
            MaxMeanTemperature(130.0),
        ],
    ),
    (
        TussockCaputus,
        all![
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
            MinMeanTemperature(180.0),
            MaxMeanTemperature(190.0),
        ],
    ),
    (
        TussockCatena,
        all![
            any![
                Region(NormaExpanse),
                Region(InnerScutumCentaurusArm),
                Region(OuterScutumCentaurusArm),
                Region(TheVoid),
                Region(HieronymusDelta),
                Region(TheVeils),
                Region(AquilasHalo),
                Region(FormorianFrontier),
                Region(TrojanBelt),
            ],
            ThinAtmosphere(Ammonia),
            PlanetClass(RockyBody),
            MaxPressure(0.0134),
            MinGravity(0.04),
            MaxGravity(0.28),
            MinMeanTemperature(152.0),
            MaxMeanTemperature(177.0),
        ],
    ),
    (
        TussockCultro,
        all![
            any![
                Region(InnerOrionSpur),
                Region(OuterOrionSpur),
                Region(GalacticCenter),
                Region(Izanami),
                Region(OrionCygnusArm),
                Region(OdinsHold),
                Region(Temple),
                Region(InnerOrionPerseusConflux),
            ],
            ThinAtmosphere(Ammonia),
            PlanetClass(RockyBody),
            MaxPressure(0.0134),
            MinGravity(0.04),
            MaxGravity(0.28),
            MinMeanTemperature(152.0),
            MaxMeanTemperature(177.0),
        ],
    ),
    (
        TussockDivisa,
        all![
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            any![
                Region(RykersHope),
                Region(OuterOrionPerseusConflux),
                Region(ElysianShore),
                Region(PerseusArm),
                Region(VulcanGate),
                Region(SanguineousRim),
                Region(AchillessAltar),
                Region(LysasSong),
                Region(Tenebrae),
            ],
            ThinAtmosphere(Ammonia),
            MinMeanTemperature(152.0),
            MaxMeanTemperature(177.0),
            MinGravity(0.04),
            MaxGravity(0.276),
        ],
    ),
    (
        TussockIgnis,
        all![
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            ThinAtmosphere(CarbonDioxide),
            MinGravity(0.04),
            MaxGravity(0.20),
            MinMeanTemperature(161.0),
            MaxMeanTemperature(170.0),
            MinPressure(0.0028),
            MaxPressure(0.055),
        ],
    ),
    (
        TussockPennata,
        all![
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
            MinMeanTemperature(145.0),
            MaxMeanTemperature(155.0),
        ],
    ),
    (
        TussockPennatis,
        all![
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            ThinAtmosphere(CarbonDioxide),
            MaxGravity(0.04),
            MaxGravity(0.276),
            MinMeanTemperature(145.0),
            MaxMeanTemperature(195.0),
        ],
    ),
    (
        TussockPropagito,
        all![
            any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody),],
            any![
                Region(GalacticCenter),
                Region(OdinsHold),
                Region(InnerScutumCentaurusArm),
                Region(OuterScutumCentaurusArm),
                Region(FormorianFrontier),
                Region(HieronymusDelta),
                Region(NormaExpanse),
                Region(TheVoid),
                Region(AquilasHalo),
                Region(TrojanBelt),
                Region(TheVeils),
            ],
            ThinAtmosphere(CarbonDioxide),
            MinGravity(0.04),
            MaxGravity(0.276),
            MinMeanTemperature(145.0),
            MaxMeanTemperature(200.0),
            MinPressure(0.003),
        ],
    ),
    (
        TussockSerrati,
        all![
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
            MinMeanTemperature(170.0),
            MaxMeanTemperature(175.0),
        ],
    ),
    (
        TussockStigmasis,
        all![
            ThinAtmosphere(SulfurDioxide),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
        ],
    ),
    (
        TussockTriticum,
        all![
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
            MinMeanTemperature(190.0),
            MaxMeanTemperature(195.0),
        ],
    ),
    (
        TussockVentusa,
        all![
            ThinAtmosphere(CarbonDioxide),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
            MinMeanTemperature(155.0),
            MaxMeanTemperature(160.0),
        ],
    ),
    (
        TussockVirgam,
        all![
            ThinAtmosphere(Water),
            PlanetClass(RockyBody),
            MaxGravity(0.276),
        ],
    ),
    (ThargoidBarnacleCommon, Special),
    (ThargoidBarnacleLarge, Special),
    (ThargoidBarnacleBarbs, Special),
    (ThargoidBarnacleMatrixSubmerged, Special),
    (ThargoidBarnacleMatrix, Special),
];
