use lazy_static::lazy_static;

use crate::exobiology::{SpawnCondition, Species};
use crate::galaxy::{AtmosphereType, PlanetClass, StarClass, StarLuminosity, VolcanismType};
use crate::materials::Material;
use AtmosphereType::*;
use PlanetClass::*;
use SpawnCondition::*;
use Species::*;

macro_rules! any {
    ($($x:expr),*) => {
        SpawnCondition::Any(vec![$($x),*])
    };
}

macro_rules! all {
    ($($x:expr),*) => {
        SpawnCondition::All(vec![$($x),*])
    };
}

lazy_static! {
    pub static ref SPECIES_SPAWN_CONDITIONS: [(Species, SpawnCondition); 122] = [
        (
            AleoidaArcus,
            all![
                ThinAtmosphere(CarbonDioxide),
                MaxGravity(0.27),
                MinMeanTemperature(175.0),
                MaxMeanTemperature(180.0)
            ]
        ),
        (
            AleoidaCoronamus,
            all![
                ThinAtmosphere(CarbonDioxide),
                MaxGravity(0.27),
                MinMeanTemperature(180.0),
                MaxMeanTemperature(190.0)
            ]
        ),
        (
            AleoidaGravis,
            all![
                ThinAtmosphere(CarbonDioxide),
                MaxGravity(0.27),
                MinMeanTemperature(190.0),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            AleoidaLaminiae,
            all![ThinAtmosphere(Ammonia), MaxGravity(0.27)]
        ),
        (
            AleoidaSpica,
            all![ThinAtmosphere(Ammonia), MaxGravity(0.27)]
        ),
        (
            AmphoraPlant,
            all![
                ParentStarClass(StarClass::A),
                NoAtmosphere,
                PlanetClass(MetalRichBody),
                any![
                    SystemContainsPlanetClass(EarthlikeBody),
                    SystemContainsPlanetClass(AmmoniaWorld),
                    SystemContainsPlanetClass(GasGiantWithWaterBasedLife,),
                    SystemContainsPlanetClass(GasGiantWithAmmoniaBasedLife,),
                    SystemContainsPlanetClass(WaterGiant)
                ]
            ]
        ),
        (
            AnemonePrasinumBioluminescent,
            all![
                NoAtmosphere,
                ParentStarClass(StarClass::O),
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody),
                    RockyComposition
                ]
            ]
        ),
        (
            AnemonePuniceum,
            all![
                NoAtmosphere,
                ParentStarClass(StarClass::O),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)]
            ]
        ),
        (
            AnemoneRoseumBioluminescent,
            all![
                NoAtmosphere,
                ParentStarClass(StarClass::B),
                any![
                    ParentStarLuminosity(StarLuminosity::I),
                    ParentStarLuminosity(StarLuminosity::II),
                    ParentStarLuminosity(StarLuminosity::III)
                ],
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody)
                ]
            ]
        ),
        (
            AnemoneRoseum,
            all![
                NoAtmosphere,
                ParentStarClass(StarClass::B),
                any![
                    ParentStarLuminosity(StarLuminosity::I),
                    ParentStarLuminosity(StarLuminosity::II),
                    ParentStarLuminosity(StarLuminosity::III)
                ],
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody)
                ]
            ]
        ),
        (
            AnemoneBlatteumBioluminescent,
            all![
                NoAtmosphere,
                ParentStarClass(StarClass::B),
                any![
                    ParentStarLuminosity(StarLuminosity::IV),
                    ParentStarLuminosity(StarLuminosity::V)
                ],
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody)
                ]
            ]
        ),
        (
            AnemoneLuteolum,
            all![
                NoAtmosphere,
                ParentStarClass(StarClass::B),
                any![
                    ParentStarLuminosity(StarLuminosity::IV),
                    ParentStarLuminosity(StarLuminosity::V)
                ],
                RockyComposition
            ]
        ),
        (
            AnemoneRubeumBioluminescent,
            all![
                NoAtmosphere,
                ParentStarClass(StarClass::B),
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody)
                ]
            ]
        ),
        (
            AnemoneCroceum,
            all![
                NoAtmosphere,
                ParentStarClass(StarClass::B),
                RockyComposition
            ]
        ),
        (BarkMound, all![NoAtmosphere, WithinNebulaRange(150.0)]),
        (BacteriumNebulus, ThinAtmosphere(Helium)),
        (
            BacteriumAcies,
            any![ThinAtmosphere(Neon), ThinAtmosphere(NeonRich)]
        ),
        (
            BacteriumOmentum,
            all![
                any![ThinAtmosphere(Neon), ThinAtmosphere(NeonRich)],
                any![
                    VolcanismType(VolcanismType::NitrogenMagma),
                    VolcanismType(VolcanismType::NitrogenGeysers),
                    VolcanismType(VolcanismType::AmmoniaMagma),
                    VolcanismType(VolcanismType::AmmoniaGeysers)
                ]
            ]
        ),
        (
            BacteriumScopulum,
            all![
                any![ThinAtmosphere(Neon), ThinAtmosphere(NeonRich)],
                any![
                    VolcanismType(VolcanismType::CarbonDioxideGeysers),
                    VolcanismType(VolcanismType::MethaneGeysers),
                    VolcanismType(VolcanismType::MethaneMagma)
                ]
            ]
        ),
        (
            BacteriumVerrata,
            all![
                any![ThinAtmosphere(Neon), ThinAtmosphere(NeonRich)],
                any![
                    VolcanismType(VolcanismType::WaterMagma),
                    VolcanismType(VolcanismType::WaterGeysers)
                ]
            ]
        ),
        (
            BacteriumBullaris,
            any![ThinAtmosphere(Methane), ThinAtmosphere(MethaneRich)]
        ),
        (BacteriumAlcyoneum, ThinAtmosphere(Ammonia)),
        (
            BacteriumVesicula,
            any![ThinAtmosphere(Argon), ThinAtmosphere(ArgonRich)]
        ),
        (
            BacteriumCerbrus,
            any![ThinAtmosphere(SulfurDioxide), ThinAtmosphere(Water)]
        ),
        (
            BacteriumAurasus,
            any![
                ThinAtmosphere(CarbonDioxide),
                ThinAtmosphere(CarbonDioxideRich)
            ]
        ),
        (BacteriumInformem, ThinAtmosphere(Nitrogen)),
        (BacteriumVolu, ThinAtmosphere(Oxygen)),
        (
            BacteriumTela,
            any![
                all![
                    ThinAtmosphere(Argon),
                    any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                    MinGravity(0.045),
                    MaxGravity(0.28),
                    MinMeanTemperature(50.0),
                    MaxMeanTemperature(150.0),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(ArgonRich),
                    MinGravity(0.24),
                    MaxGravity(0.45),
                    MinMeanTemperature(50.0),
                    MaxMeanTemperature(150.0),
                    MaxPressure(0.05),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(Ammonia),
                    MinGravity(0.025),
                    MaxGravity(0.23),
                    MinMeanTemperature(165.0),
                    MaxMeanTemperature(177.0),
                    MinPressure(0.0025),
                    MaxPressure(0.02),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(CarbonDioxide),
                    MinGravity(0.45),
                    MaxGravity(0.61),
                    MinMeanTemperature(300.0),
                    MaxMeanTemperature(500.0),
                    MinPressure(0.006),
                    VolcanismType(VolcanismType::None)
                ],
                all![
                    any![
                        ThinAtmosphere(CarbonDioxide),
                        ThinAtmosphere(CarbonDioxideRich)
                    ],
                    MinGravity(0.26),
                    MaxGravity(0.57),
                    MinMeanTemperature(167.0),
                    MaxMeanTemperature(300.0),
                    MinPressure(0.006),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(Helium),
                    PlanetClass(IcyBody),
                    MinGravity(0.025),
                    MaxGravity(0.61),
                    MinMeanTemperature(20.0),
                    MaxMeanTemperature(21.0),
                    MinPressure(0.067),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(Methane),
                    any![
                        PlanetClass(IcyBody),
                        PlanetClass(RockyBody),
                        PlanetClass(HighMetalContentBody)
                    ],
                    MinGravity(0.026),
                    MaxGravity(0.126),
                    MinMeanTemperature(80.0),
                    MaxMeanTemperature(109.0),
                    MinPressure(0.012),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(Neon),
                    any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                    MinGravity(0.27),
                    MaxGravity(0.61),
                    MinMeanTemperature(20.0),
                    MaxMeanTemperature(95.0),
                    MaxPressure(0.008),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(NeonRich),
                    any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                    MinGravity(0.27),
                    MaxGravity(0.61),
                    MinMeanTemperature(20.0),
                    MaxMeanTemperature(95.0),
                    MinPressure(0.003),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(Nitrogen),
                    MinGravity(0.21),
                    MaxGravity(0.35),
                    MinMeanTemperature(55.0),
                    MaxMeanTemperature(80.0),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(Oxygen),
                    MinGravity(0.23),
                    MaxGravity(0.5),
                    MinMeanTemperature(150.0),
                    MaxMeanTemperature(240.0),
                    MinPressure(0.01),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(SulfurDioxide),
                    MinGravity(0.18),
                    MaxGravity(0.61),
                    MinMeanTemperature(148.0),
                    MaxMeanTemperature(500.0),
                    AnyVolcanism
                ],
                all![
                    ThinAtmosphere(SulfurDioxide),
                    MinGravity(0.18),
                    MaxGravity(0.61),
                    MinMeanTemperature(300.0),
                    MaxMeanTemperature(500.0),
                    VolcanismType(VolcanismType::None)
                ],
                all![
                    ThinAtmosphere(Water),
                    any![PlanetClass(RockyBody), PlanetClass(HighMetalContentBody)],
                    MinGravity(0.04),
                    MaxGravity(0.063),
                    VolcanismType(VolcanismType::None)
                ],
                all![
                    ThinAtmosphere(WaterRich),
                    any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                    MinGravity(0.32),
                    MaxGravity(0.44),
                    MinMeanTemperature(240.0),
                    MaxMeanTemperature(330.0),
                    MinPressure(0.01),
                    AnyVolcanism
                ]
            ]
        ),
        (BrainTreeAureum, all![NoAtmosphere, AnyVolcanism]),
        (BrainTreeOstrinum, all![NoAtmosphere, AnyVolcanism]),
        (BrainTreePuniceum, all![NoAtmosphere, AnyVolcanism]),
        (BrainTreeLindigoticum, all![NoAtmosphere, AnyVolcanism]),
        (BrainTreeGypseeum, all![NoAtmosphere, AnyVolcanism]),
        (BrainTreeLividum, all![NoAtmosphere, AnyVolcanism]),
        (BrainTreeViride, all![NoAtmosphere, AnyVolcanism]),
        (BrainTreeRoseum, all![NoAtmosphere, AnyVolcanism]),
        (
            CactoidaLapis,
            all![
                MaxGravity(0.27),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                ThinAtmosphere(Ammonia)
            ]
        ),
        (
            CactoidaPullulanta,
            all![
                MaxGravity(0.27),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                any![
                    ThinAtmosphere(CarbonDioxide),
                    ThinAtmosphere(CarbonDioxideRich)
                ],
                MinMeanTemperature(180.0),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            CactoidaCortexum,
            all![
                MaxGravity(0.27),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                any![
                    ThinAtmosphere(CarbonDioxide),
                    ThinAtmosphere(CarbonDioxideRich)
                ],
                MinMeanTemperature(180.0),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            CactoidaVermis,
            all![
                MaxGravity(0.27),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                ThinAtmosphere(Water)
            ]
        ),
        (
            CactoidaPeperatis,
            all![
                MaxGravity(0.27),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                ThinAtmosphere(Ammonia)
            ]
        ),
        (
            ClypeusSpeculumi,
            all![
                MaxGravity(0.27),
                MinMeanTemperature(190.0),
                any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Water)],
                MinDistanceFromParentSun(5.0)
            ]
        ),
        (
            ClypeusLacrimam,
            all![
                MaxGravity(0.27),
                MinMeanTemperature(190.0),
                any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Water)]
            ]
        ),
        (
            ClypeusMargaritus,
            all![
                MaxGravity(0.27),
                MinMeanTemperature(190.0),
                any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Water)]
            ]
        ),
        (
            ConchaRenibus,
            any![
                all![
                    MaxGravity(0.27),
                    any![
                        ThinAtmosphere(CarbonDioxide),
                        ThinAtmosphere(CarbonDioxideRich)
                    ],
                    MinMeanTemperature(180.0),
                    MaxMeanTemperature(195.0)
                ],
                all![
                    MaxGravity(0.27),
                    any![ThinAtmosphere(Water), ThinAtmosphere(WaterRich)]
                ]
            ]
        ),
        (
            ConchaAureolas,
            all![MaxGravity(0.27), ThinAtmosphere(Ammonia)]
        ),
        (
            ConchaLabiata,
            all![
                MaxGravity(0.27),
                any![
                    ThinAtmosphere(CarbonDioxide),
                    ThinAtmosphere(CarbonDioxideRich)
                ],
                MaxMeanTemperature(190.0)
            ]
        ),
        (
            ConchaBiconcavis,
            all![MaxGravity(0.27), ThinAtmosphere(Nitrogen)]
        ),
        (
            CrystallineShards,
            all![
                NoAtmosphere,
                any![
                    ParentStarClass(StarClass::A),
                    ParentStarClass(StarClass::F),
                    ParentStarClass(StarClass::G),
                    ParentStarClass(StarClass::K),
                    ParentStarClass(StarClass::M),
                    ParentStarClass(StarClass::S)
                ],
                MinMeanTemperature(0.0),
                MaxMeanTemperature(273.0),
                any![
                    SystemContainsPlanetClass(EarthlikeBody),
                    SystemContainsPlanetClass(AmmoniaWorld),
                    SystemContainsPlanetClass(GasGiantWithWaterBasedLife,),
                    SystemContainsPlanetClass(GasGiantWithAmmoniaBasedLife,),
                    SystemContainsPlanetClass(WaterGiant)
                ],
                MinDistanceFromParentSun(24.0)
            ]
        ),
        (
            ElectricaePluma,
            all![
                any![
                    ThinAtmosphere(Helium),
                    ThinAtmosphere(Neon),
                    ThinAtmosphere(Argon)
                ],
                PlanetClass(IcyBody),
                ParentStarClass(StarClass::A),
                any![
                    MinOrEqualParentStarLuminosity(StarLuminosity::V),
                    ParentStarClass(StarClass::N)
                ],
                MaxGravity(0.27)
            ]
        ),
        (
            ElectricaeRadialem,
            all![
                any![
                    ThinAtmosphere(Helium),
                    ThinAtmosphere(Neon),
                    ThinAtmosphere(Argon)
                ],
                PlanetClass(IcyBody),
                WithinNebulaRange(150.0),
                MaxGravity(0.27)
            ]
        ),
        (
            FonticuluaCampestris,
            all![
                ThinAtmosphere(Argon),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            FonticuluaSegmentatus,
            all![
                any![ThinAtmosphere(Neon), ThinAtmosphere(NeonRich)],
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            FonticuluaDigitos,
            all![
                any![ThinAtmosphere(Methane), ThinAtmosphere(MethaneRich)],
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            FonticuluaUpupam,
            all![
                ThinAtmosphere(ArgonRich),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            FonticuluaLapida,
            all![
                ThinAtmosphere(Nitrogen),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            FonticuluaFluctus,
            all![
                ThinAtmosphere(Oxygen),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            FrutexaAcus,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            FrutexaCollum,
            all![
                ThinAtmosphere(SulfurDioxide),
                RockyComposition,
                MaxGravity(0.27)
            ]
        ),
        (
            FrutexaFera,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            FrutexaFlabellum,
            all![ThinAtmosphere(Ammonia), RockyComposition, MaxGravity(0.27)]
        ),
        (
            FrutexaFlammasis,
            all![ThinAtmosphere(Ammonia), RockyComposition, MaxGravity(0.27)]
        ),
        (
            FrutexaMetallicum,
            all![
                any![
                    all![ThinAtmosphere(CarbonDioxide), MaxMeanTemperature(195.0)],
                    ThinAtmosphere(Ammonia)
                ],
                PlanetClass(HighMetalContentBody),
                MaxGravity(0.27)
            ]
        ),
        (
            FrutexaSponsae,
            all![ThinAtmosphere(Water), RockyComposition, MaxGravity(0.27)]
        ),
        (
            FumerolaAquatis,
            all![
                AnyThinAtmosphere,
                GeologicalSignalsPresent,
                any![
                    VolcanismType(VolcanismType::WaterMagma),
                    VolcanismType(VolcanismType::WaterGeysers)
                ],
                MaxGravity(0.27)
            ]
        ),
        (
            FumerolaCarbosis,
            all![
                AnyThinAtmosphere,
                GeologicalSignalsPresent,
                any![
                    VolcanismType(VolcanismType::CarbonDioxideGeysers),
                    VolcanismType(VolcanismType::MethaneMagma),
                    VolcanismType(VolcanismType::MethaneGeysers)
                ],
                MaxGravity(0.27)
            ]
        ),
        (
            FumerolaExtremus,
            all![
                AnyThinAtmosphere,
                GeologicalSignalsPresent,
                any![
                    MaterialPresence(Material::Iron),
                    VolcanismType(VolcanismType::CarbonDioxideGeysers),
                    VolcanismType(VolcanismType::MethaneMagma),
                    VolcanismType(VolcanismType::MethaneGeysers)
                ],
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            FumerolaNitris,
            all![
                AnyThinAtmosphere,
                GeologicalSignalsPresent,
                any![
                    VolcanismType(VolcanismType::NitrogenMagma),
                    VolcanismType(VolcanismType::NitrogenGeysers),
                    VolcanismType(VolcanismType::AmmoniaMagma),
                    VolcanismType(VolcanismType::AmmoniaGeysers)
                ],
                MaxGravity(0.27)
            ]
        ),
        (
            FungoidaBullarum,
            all![
                any![ThinAtmosphere(Argon), ThinAtmosphere(ArgonRich)],
                MaxGravity(0.27)
            ]
        ),
        (
            FungoidaGelata,
            all![
                any![
                    ThinAtmosphere(Water),
                    all![
                        ThinAtmosphere(CarbonDioxide),
                        MinMeanTemperature(180.0),
                        MaxMeanTemperature(195.0)
                    ]
                ],
                MaxGravity(0.27)
            ]
        ),
        (
            FungoidaSetisis,
            all![
                any![ThinAtmosphere(Ammonia), ThinAtmosphere(Methane)],
                MaxGravity(0.27)
            ]
        ),
        (
            FungoidaStabitis,
            all![
                any![
                    ThinAtmosphere(Water),
                    all![
                        ThinAtmosphere(CarbonDioxide),
                        MinMeanTemperature(180.0),
                        MaxMeanTemperature(195.0)
                    ]
                ],
                MaxGravity(0.27)
            ]
        ),
        (
            OsseusCornibus,
            all![
                ThinAtmosphere(CarbonDioxide),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                MaxGravity(0.27),
                MinMeanTemperature(180.0),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            OsseusDiscus,
            all![
                ThinAtmosphere(Water),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            OsseusFractus,
            all![
                ThinAtmosphere(CarbonDioxide),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                MaxGravity(0.27),
                MinMeanTemperature(180.0),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            OsseusPellebantus,
            all![
                ThinAtmosphere(CarbonDioxide),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                MaxGravity(0.27),
                MinMeanTemperature(180.0),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            OsseusPumice,
            all![
                any![
                    ThinAtmosphere(Argon),
                    ThinAtmosphere(Methane),
                    ThinAtmosphere(Nitrogen)
                ],
                any![
                    RockyComposition,
                    PlanetClass(HighMetalContentBody),
                    PlanetClass(RockyIceBody)
                ],
                MaxGravity(0.27)
            ]
        ),
        (
            OsseusSpiralis,
            all![
                ThinAtmosphere(Ammonia),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            ReceptaConditivus,
            all![
                ThinAtmosphere(SulfurDioxide),
                any![PlanetClass(IcyBody), PlanetClass(RockyIceBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            ReceptaDeltahedronix,
            all![
                ThinAtmosphere(SulfurDioxide),
                any![RockyComposition, PlanetClass(HighMetalContentBody)],
                MaxGravity(0.27)
            ]
        ),
        (
            ReceptaUmbrux,
            all![ThinAtmosphere(SulfurDioxide), MaxGravity(0.27)]
        ),
        (SinuousTubersAlbidum, all![NoAtmosphere, RockyComposition]),
        (
            SinuousTubersBlatteum,
            all![
                NoAtmosphere,
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody)
                ]
            ]
        ),
        (SinuousTubersCaeruleum, all![NoAtmosphere, RockyComposition]),
        (
            SinuousTubersLindigoticum,
            all![NoAtmosphere, RockyComposition]
        ),
        (
            SinuousTubersPrasinum,
            all![
                NoAtmosphere,
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody)
                ]
            ]
        ),
        (
            SinuousTubersRoseum,
            all![NoAtmosphere, VolcanismType(VolcanismType::SilicateMagma)]
        ),
        (
            SinuousTubersViolaceum,
            all![
                NoAtmosphere,
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody)
                ]
            ]
        ),
        (
            SinuousTubersViride,
            all![
                NoAtmosphere,
                any![
                    PlanetClass(MetalRichBody),
                    PlanetClass(HighMetalContentBody)
                ]
            ]
        ),
        (
            StratumAraneamus,
            all![
                ThinAtmosphere(SulfurDioxide),
                RockyComposition,
                MinMeanTemperature(165.0)
            ]
        ),
        (
            StratumCucumisis,
            all![
                any![ThinAtmosphere(SulfurDioxide), ThinAtmosphere(CarbonDioxide)],
                RockyComposition,
                MinMeanTemperature(190.0)
            ]
        ),
        (
            StratumExcutitus,
            all![
                any![ThinAtmosphere(SulfurDioxide), ThinAtmosphere(CarbonDioxide)],
                RockyComposition,
                MinMeanTemperature(165.0),
                MaxMeanTemperature(190.0)
            ]
        ),
        (
            StratumFrigus,
            all![
                any![ThinAtmosphere(SulfurDioxide), ThinAtmosphere(CarbonDioxide)],
                RockyComposition,
                MinMeanTemperature(190.0)
            ]
        ),
        (
            StratumLaminamus,
            all![
                ThinAtmosphere(Ammonia),
                RockyComposition,
                MinMeanTemperature(165.0)
            ]
        ),
        (
            StratumLimaxus,
            all![
                any![ThinAtmosphere(SulfurDioxide), ThinAtmosphere(CarbonDioxide)],
                RockyComposition,
                MinMeanTemperature(165.0),
                MaxMeanTemperature(190.0)
            ]
        ),
        (
            StratumPaleas,
            all![
                any![
                    ThinAtmosphere(Ammonia),
                    ThinAtmosphere(Water),
                    ThinAtmosphere(CarbonDioxide)
                ],
                RockyComposition,
                MinMeanTemperature(165.0)
            ]
        ),
        (
            StratumTectonicas,
            all![
                AnyThinAtmosphere,
                PlanetClass(HighMetalContentBody),
                MinMeanTemperature(165.0)
            ]
        ),
        (
            TubusCavas,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.15),
                MinMeanTemperature(160.0),
                MaxMeanTemperature(190.0)
            ]
        ),
        (
            TubusCompagibus,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.15),
                MinMeanTemperature(160.0),
                MaxMeanTemperature(190.0)
            ]
        ),
        (
            TubusConifer,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MinGravity(0.041),
                MaxGravity(0.15),
                MinMeanTemperature(160.0),
                MaxMeanTemperature(190.0),
                VolcanismType(VolcanismType::None),
                MinPressure(0.003)
            ]
        ),
        (
            TubusRosarium,
            all![
                ThinAtmosphere(Ammonia),
                RockyComposition,
                MaxGravity(0.15),
                MinMeanTemperature(160.0)
            ]
        ),
        (
            TubusSororibus,
            all![
                any![ThinAtmosphere(CarbonDioxide), ThinAtmosphere(Ammonia)],
                PlanetClass(HighMetalContentBody),
                MaxGravity(0.15),
                MinMeanTemperature(160.0),
                MaxMeanTemperature(190.0)
            ]
        ),
        (
            TussockAlbata,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MinMeanTemperature(175.0),
                MaxMeanTemperature(180.0)
            ]
        ),
        (
            TussockCapillum,
            all![
                any![ThinAtmosphere(Argon), ThinAtmosphere(Methane)],
                RockyComposition,
                MaxGravity(0.27)
            ]
        ),
        (
            TussockCaputus,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MinMeanTemperature(180.0),
                MaxMeanTemperature(190.0)
            ]
        ),
        (
            TussockCatena,
            all![ThinAtmosphere(Ammonia), RockyComposition, MaxGravity(0.27)]
        ),
        (
            TussockCultro,
            all![ThinAtmosphere(Ammonia), RockyComposition, MaxGravity(0.27)]
        ),
        (
            TussockDivisa,
            all![ThinAtmosphere(Ammonia), RockyComposition, MaxGravity(0.27)]
        ),
        (
            TussockIgnis,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MinMeanTemperature(160.0),
                MaxMeanTemperature(170.0)
            ]
        ),
        (
            TussockPennata,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MinMeanTemperature(145.0),
                MaxMeanTemperature(155.0)
            ]
        ),
        (
            TussockPennatis,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            TussockPropagito,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            TussockSerrati,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MinMeanTemperature(170.0),
                MaxMeanTemperature(175.0)
            ]
        ),
        (
            TussockStigmasis,
            all![
                ThinAtmosphere(SulfurDioxide),
                RockyComposition,
                MaxGravity(0.27)
            ]
        ),
        (
            TussockTriticum,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MinMeanTemperature(190.0),
                MaxMeanTemperature(195.0)
            ]
        ),
        (
            TussockVentusa,
            all![
                ThinAtmosphere(CarbonDioxide),
                RockyComposition,
                MaxGravity(0.27),
                MinMeanTemperature(155.0),
                MaxMeanTemperature(160.0)
            ]
        ),
        (
            TussockVirgam,
            all![ThinAtmosphere(Water), RockyComposition, MaxGravity(0.27)]
        ),
        (ThargoidBarnacleCommon, Special),
        (ThargoidBarnacleLarge, Special),
        (ThargoidBarnacleBarbs, Special),
        (ThargoidBarnacleMatrixSubmerged, Special),
        (ThargoidBarnacleMatrix, Special)
    ];
}
