use std::fmt::{Display, Formatter};
use std::str::FromStr;

use lazy_static::lazy_static;
use regex::Regex;
use thiserror::Error;

use crate::from_str_deserialize_impl;

#[derive(Debug, Clone, PartialEq)]
pub enum Commodity {
    // Chemicals
    ArgonomicTreatment,
    Explosives,
    HydrogenFuel,
    HydrogenPeroxide,
    LiquidOxygen,
    MineralOil,
    NerveAgents,
    Pesticides,
    RockforthFertiliser,
    SurfaceStabilisers,
    SyntheticReagents,
    Tritium,
    Water,

    // Consumer items
    Clothing,
    ConsumerTechnology,
    DomesticAppliances,
    EvacuationShelter,
    SurvivalEquipment,

    // Legal drugs
    Beer,
    BootlegLiquor,
    Liquor,
    Narcotics,
    OnionheadGammaStrain,
    Tobacco,
    Wine,

    // Foods
    Algae,
    AnimalMeat,
    Coffee,
    Fish,
    FoodCartridges,
    FruitAndVegetables,
    Grain,
    SyntheticMeat,
    Tea,

    // Industrial materials
    CeramicComposites,
    CMMComposite,
    InsulatingMembrane,
    MetaAlloys,
    MicroWeaveCoolingHoses,
    NeofabricInsulation,
    Polymers,
    Semiconductors,
    Superconductors,

    // Machinery
    ArticulationMotors,
    AtmosphericProcessors,
    BuildingFabricators,
    CropHarvesters,
    EmergencyPowerCells,
    EnergyGridAssembly,
    ExhaustManifold,
    GeologicalEquipment,
    HeatsinkInterlink,
    HNShockMount,
    IonDistributor,
    MagneticEmitterCoil,
    MarineEquipment,
    MicrobialFurnaces,
    MineralExtractors,
    ModularTerminals,
    PowerConverter,
    PowerGenerators,
    PowerTransferBus,
    RadiationBaffle,
    ReinforcedMountingPlate,
    SkimmerComponents,
    ThermalCoolingUnits,
    WaterPurifiers,

    // Medicines
    AdvancedMedicines,
    AgriMedicines,
    BasicMedicines,
    CombatStabilisers,
    PerformanceEnhancers,
    ProgenitorCells,

    // Metals
    Aluminium,
    Beryllium,
    Bismuth,
    Cobalt,
    Copper,
    Gallium,
    Gold,
    Hafnium178,
    Indium,
    Lanthanum,
    Lithium,
    Osmium,
    Palladium,
    Platinum,
    Praseodymium,
    Samarium,
    Silver,
    Tantalum,
    Thallium,
    Thorium,
    Titanium,
    Uranium,

    // Minerals
    Alexandrite,
    Bauxite,
    Benitoite,
    Bertrandite,
    Bromellite,
    Coltan,
    Cryolite,
    Gallite,
    Goslarite,
    Grandidierite,
    Indite,
    Jadeite,
    Lepidolite,
    LithiumHydroxide,
    LowTemperatureDiamonds,
    MethaneClathrate,
    MethanolMonohydrateCrystals,
    Moissanite,
    Monazite,
    Musgravite,
    Painite,
    Pyrophyllite,
    Rhodplumsite,
    Rutile,
    Serendibite,
    Taaffeite,
    Uraninite,
    VoidOpal,

    // Salvage
    AIRelics,
    AncientArtefact,
    AncientKey,
    AnomalyParticles,
    AntimatterContainmentUnit,
    AniqueJewellery,
    Antiquities,
    AssaultPlans,
    BlackBox,
    BoneFragments,
    CausticTissueSample,
    CommercialSamples,
    CoralSap,
    CystSpecimen,
    DamagedEscapePod,
    DataCore,
    DiplomaticBag,
    EarthRelics,
    EncryptedCorrespondence,
    EncryptedDataStorage,
    ExperimentalChemicals,
    FossilRemnants,
    GeneBank,
    GeologicalSamples,
    GuardianCasket,
    GuardianOrb,
    GuardianRelic,
    GuardianTablet,
    GuardianTotem,
    GuardianUrn,
    Hostages,
    ImpureSpireMineral,
    LargeSurveyDataCache,
    MilitaryIntelligence,
    MilitaryPlans,
    MolluscBrainTissue,
    MolluscFluid,
    MolluscMembrane,
    MolluscMycelium,
    MolluscSoftTissue,
    MolluscSpores,
    MysteriousIdol,
    OccupiedEscapePod,
    OrganSample,
    PersonalEffects,
    PodCoreTissue,
    PodDeadTissue,
    PodMesoglea,
    PodOuterTissue,
    PodShellTissue,
    PodSurfaceTissue,
    PodTissue,
    PoliticalPrisoners,
    PreciousGems,
    ProhibitedResearchMaterials,
    ProtectiveMembraneScrap,
    PrototypeTech,
    RareArtwork,
    RebelTransmission,
    SAP8CoreContainer,
    ScientificResearch,
    ScientificSamples,
    SemiRefinesSpireMineral,
    SmallSurveyDataCache,
    SpacePioneerRelics,
    TacticalData,
    TechnicalBlueprints,
    ThargoidBasiliskTissueSample,
    ThargoidBioStorageCapsule,
    ThargoidBiologicalMatter,
    ThargoidCyclopsTissueSample,
    ThargoidGlaiveTissueSample,
    ThargoidHeart,
    ThargoidHydraTissueSample,
    ThargoidLink,
    ThargoidMedusaTissueSample,
    ThargoidOrthrusTissueSample,
    ThargoidProbe,
    ThargoidResin,
    ThargoidScoutTissueSample,
    ThargoidScytheTissueSample,
    ThargoidGeneratorTissueSample,
    ThargoidSensor,
    ThargoidTechnologySamples,
    TimeCapsule,
    TitanDeepTissueSample,
    TitanDriveComponent,
    TitanMawDeepTissueSample,
    TitanMawPartialTissueSample,
    TitanMawTissueSample,
    TitanPartialTissueSample,
    TitanTissueSample,
    TradeData,
    TrinketsOfHiddenFortune,
    UnclassifiedRelic,
    UnoccupiedEscapePod,
    UnstableDataCore,
    WreckageComponents,

    // Slaves
    ImperialSlaves,
    Slaves,

    // Technology
    AdvancedCatalysers,
    AnimalMonitors,
    AquaponicSystems,
    AutoFabricators,
    BioreducingLichen,
    ComputerComponents,
    HESuits,
    HardwareDiagnosticSensor,
    LandEnrichmentSystems,
    MedialDiagnosticEquipment,
    MicroControllers,
    MuonImager,
    Nanobreakers,
    ResonatingSeparators,
    Robotics,
    StructuralRegulators,
    TelemetrySuite,
    // Textiles
    ConductiveFabrics,
    Leather,
    MilitaryGradeFabrics,
    NaturalFabrics,
    SyntheticFabrics,
    // Waste
    Biowaste,
    ChemicalWaste,
    Scrap,
    ToxicWaste,
    // Weapons
    BattleWeapons,
    Landmines,
    NonLethalWeapons,
    PersonalWeapons,
    ReactiveArmour,
    // Rare
    JaquesQuinentianStill,
    KinagoViolins,
    ApaVietii,
    GeawenDanceDust,
    VanayequiCeratomorphaFur,
    KaretiiCouture,
    MukusubiiChitinos,
    UltraCompactProcessorPrototypes,
    EleuThermals,
    KamorinHistoricWeapons,
    CeremonialHeikeTea,
    VidavantianLace,
    KachiriginFilterLeeches,
    LyraeWeed,
    GalacticTravelGuide,
    HarmaSilverSeaRum,
    NgadandariFireOpals,
    AlyaBodySoap,
    HelvetitjPearls,
    OchoengChillies,
    OnionheadBetaStrain,
    KamitraCigars,
    NjangariSaddles,
    HipOrganophosphates,
    GilyaSignatureWeapons,
    HR7221Wheat,
    WheemeteWheatCakes,
    RajukruMultiStoves,
    Nanomedicines,
    NonEuclidianExotanks,
    NgunaModernAntiques,
    XiheBiomorphicCompanions,
    EsusekuCaviar,
    OrrerianViciousBrew,
    VHerculisBodyRub,
    VoidExtractCoffee,
    UszaianTreeGrub,
    HaidenBlackBrew,
    MotronaExperienceJelly,
    JaradharrePuzzleBox,
    PersonalGifts,
    MulachiGiantFungus,
    LTTHyperSweet,
    MedbStarlube,
    GiantVerrix,
    HIP118311Swarm,
    DisoMaCorn,
    LavianBrandy,
    AzureMilk,
    LeestianEvilJuice,
    CoquimSpongiformVictuals,
    LeatheryEggs,
    ShansCharisOrchid,
    KonggaAle,
    VegaSlimweed,
    TiolceWaste2PasteUnits,
    OphiuchExinoArtefacts,
    AltairianSkin,
    AganippeRush,
    CD75KittenBrandCoffee,
    HavasupaiDreamCatcher,
    EraninPearlWhisky,
    PavonisEarGrubs,
    OnionheadAlphaStrain,
    IndiBourbon,
    BakedGreebles,
    KarsukiLocusts,
    MasterChefs,
    YasoKondiLeaf,
    BurnhamBileDistillate,
    TheHuttonMug,
    CentauriMegaGin,
    UtgaroarMillennialEggs,
    SoontillRelics,
    ZeesszeAntGrubGlue,
    TheWatersOfShintara,
    BaltahsineVacuumKrill,
    SanumaDecorativeMeat,
    GiantIrukamaSnails,
    AnduligaFireWorks,
    CrystallineSpheres,
    PantaaPrayerSticks,
    ChiEridaniMarinePaste,
    EthgrezeTeaBuds,
    DeltaPhoenicisPalms,
    TarachSpice,
    WulpaHyperboreSystems,
    LiveHecateSeaWorms,
    KoroKungPellets,
    BastSnakeGin,
    TerraMaterBloodBores,
    WuthieloKuFroth,
    HonestyPills,
    CromSilverFesh,
    BorasetaniPathogenetics,
    CetiRabbits,
    AepyornisEgg,
    UzumokuLowGWings,
    CherbonesBloodCrystals,
    ToxandjiVirocide,
    Onionhead,
    LucanOnionhead,
    TanmarkTranquilTea,
    ThrutisCream,
    AlacarakmoSkinArt,
    PlatinumAlloy,
    MokojingBeastFeast,
    EdenApplesOfAerial,
    ChameleonCloth,
    TauriChimes,
    RusaniOldSmokey,
    AZCancriFormula42,
    GomanYauponCoffee,
    GerasianGueuzeBeer,
    JarouaRice,
    AnyNaCoffee,
    FujinTea,
    HIP10175BushMeat,
    MomusBogSpaniel,
    WitchhaulKobeBeef,
    SaxonWine,
    AroucaConventualSweets,
    AlbinoQuechuaMammothMeat,
    Duradrives,
    HolvaDuellingBlades,
    RapaBaoSnakeSkins,
    WolfFesh,
    EshuUmbrellas,
    NeritusBerries,
    JotunMookah,
    ChateauDeAegaeon,
    BelalansRayLeather,
    DamnaCarapaces,
    HIPProtoSquid,
    MechucosHighTea,
    DeuringasTruffles,
    BankiAmphibiousLeather,
    SothisCrystallineGold,
    TiegfriesSynthSilk,
    VolkhabBeeDrones,
    BuckyballBeerMats,
    ClassifiedExperimentalEquipment,

    // None
    Limpet,

    #[cfg(not(feature = "strict"))]
    Unknown(String),
}

#[derive(Debug, Error)]
pub enum CommodityError {
    #[error("Unknown commodity: '{0}'")]
    UnknownCommodity(String),
}

impl Commodity {
    fn name_to_commodity(name: &str) -> Result<Commodity, CommodityError> {
        let lower_case: &str = &name.to_ascii_lowercase();

        match lower_case {
            "argonomictreatment" => Ok(Commodity::ArgonomicTreatment),
            "explosives" => Ok(Commodity::Explosives),
            "hydrogenfuel" => Ok(Commodity::HydrogenFuel),
            "hydrogenperoxide" => Ok(Commodity::HydrogenPeroxide),
            "liquidoxygen" => Ok(Commodity::LiquidOxygen),
            "mineraloil" => Ok(Commodity::MineralOil),
            "nerveagents" => Ok(Commodity::NerveAgents),
            "pesticides" => Ok(Commodity::Pesticides),
            "rockforthfertiliser" => Ok(Commodity::RockforthFertiliser),
            "surfacestabilisers" => Ok(Commodity::SurfaceStabilisers),
            "syntheticreagents" => Ok(Commodity::SyntheticReagents),
            "tritium" => Ok(Commodity::Tritium),
            "water" => Ok(Commodity::Water),
            "clothing" => Ok(Commodity::Clothing),
            "consumertechnology" => Ok(Commodity::ConsumerTechnology),
            "domesticappliances" => Ok(Commodity::DomesticAppliances),
            "evacuationshelter" => Ok(Commodity::EvacuationShelter),
            "survivalequipment" => Ok(Commodity::SurvivalEquipment),
            "beer" => Ok(Commodity::Beer),
            "bootlegliquor" => Ok(Commodity::BootlegLiquor),
            "liquor" => Ok(Commodity::Liquor),
            "basicnarcotics" => Ok(Commodity::Narcotics),
            "onionheadc" => Ok(Commodity::OnionheadGammaStrain),
            "tobacco" => Ok(Commodity::Tobacco),
            "wine" => Ok(Commodity::Wine),
            "algae" => Ok(Commodity::Algae),
            "animalmeat" => Ok(Commodity::AnimalMeat),
            "coffee" => Ok(Commodity::Coffee),
            "fish" => Ok(Commodity::Fish),
            "foodcartridges" => Ok(Commodity::FoodCartridges),
            "fruitandvegetables" => Ok(Commodity::FruitAndVegetables),
            "grain" => Ok(Commodity::Grain),
            "syntheticmeat" => Ok(Commodity::SyntheticMeat),
            "tea" => Ok(Commodity::Tea),
            "ceramiccomposites" => Ok(Commodity::CeramicComposites),
            "cmmcomposite" => Ok(Commodity::CMMComposite),
            "insulatingmembrane" => Ok(Commodity::InsulatingMembrane),
            "metaalloys" => Ok(Commodity::MetaAlloys),
            "microweavecollinghoses" => Ok(Commodity::MicroWeaveCoolingHoses),
            "neofabricinsulation" => Ok(Commodity::NeofabricInsulation),
            "polymers" => Ok(Commodity::Polymers),
            "semiconductors" => Ok(Commodity::Semiconductors),
            "superconductors" => Ok(Commodity::Superconductors),
            "articulationmotors" => Ok(Commodity::ArticulationMotors),
            "atmosphericprocessors" => Ok(Commodity::AtmosphericProcessors),
            "buildingfabricators" => Ok(Commodity::BuildingFabricators),
            "cropharvesters" => Ok(Commodity::CropHarvesters),
            "emergencypowercells" => Ok(Commodity::EmergencyPowerCells),
            "energygridassembly" => Ok(Commodity::EnergyGridAssembly),
            "exhaustmanifold" => Ok(Commodity::ExhaustManifold),
            "geologicalequipment" => Ok(Commodity::GeologicalEquipment),
            "heatsinkinterlink" => Ok(Commodity::HeatsinkInterlink),
            "hnshockmount" => Ok(Commodity::HNShockMount),
            "iondistributor" => Ok(Commodity::IonDistributor),
            "magneticemittercoil" => Ok(Commodity::MagneticEmitterCoil),
            "marineequipment" => Ok(Commodity::MarineEquipment),
            "microbialfurnaces" => Ok(Commodity::MicrobialFurnaces),
            "mineralextractors" => Ok(Commodity::MineralExtractors),
            "modularterminals" => Ok(Commodity::ModularTerminals),
            "powerconverter" => Ok(Commodity::PowerConverter),
            "powergenerators" => Ok(Commodity::PowerGenerators),
            "powertransferbus" => Ok(Commodity::PowerTransferBus),
            "radiationbaffle" => Ok(Commodity::RadiationBaffle),
            "reinforcedmountingplate" => Ok(Commodity::ReinforcedMountingPlate),
            "skimmercomponents" => Ok(Commodity::SkimmerComponents),
            "thermalcoolingunits" => Ok(Commodity::ThermalCoolingUnits),
            "waterpurifiers" => Ok(Commodity::WaterPurifiers),
            "advancedmedicines" => Ok(Commodity::AdvancedMedicines),
            "agrimedicines" => Ok(Commodity::AgriMedicines),
            "basicmedicines" => Ok(Commodity::BasicMedicines),
            "combatstabilisers" => Ok(Commodity::CombatStabilisers),
            "performanceenhancers" => Ok(Commodity::PerformanceEnhancers),
            "progenitorcells" => Ok(Commodity::ProgenitorCells),
            "aluminium" => Ok(Commodity::Aluminium),
            "beryllium" => Ok(Commodity::Beryllium),
            "bismuth" => Ok(Commodity::Bismuth),
            "cobalt" => Ok(Commodity::Cobalt),
            "copper" => Ok(Commodity::Copper),
            "gallium" => Ok(Commodity::Gallium),
            "gold" => Ok(Commodity::Gold),
            "hafnium178" => Ok(Commodity::Hafnium178),
            "indium" => Ok(Commodity::Indium),
            "lanthanum" => Ok(Commodity::Lanthanum),
            "lithium" => Ok(Commodity::Lithium),
            "osmium" => Ok(Commodity::Osmium),
            "palladium" => Ok(Commodity::Palladium),
            "platinum" => Ok(Commodity::Platinum),
            "praseodymium" => Ok(Commodity::Praseodymium),
            "samarium" => Ok(Commodity::Samarium),
            "silver" => Ok(Commodity::Silver),
            "tantalum" => Ok(Commodity::Tantalum),
            "thallium" => Ok(Commodity::Thallium),
            "thorium" => Ok(Commodity::Thorium),
            "titanium" => Ok(Commodity::Titanium),
            "uranium" => Ok(Commodity::Uranium),
            "alexandrite" => Ok(Commodity::Alexandrite),
            "bauxite" => Ok(Commodity::Bauxite),
            "benitoite" => Ok(Commodity::Benitoite),
            "bertrandite" => Ok(Commodity::Bertrandite),
            "bromellite" => Ok(Commodity::Bromellite),
            "coltan" => Ok(Commodity::Coltan),
            "cryolite" => Ok(Commodity::Cryolite),
            "gallite" => Ok(Commodity::Gallite),
            "goslarite" => Ok(Commodity::Goslarite),
            "grandidierite" => Ok(Commodity::Grandidierite),
            "indite" => Ok(Commodity::Indite),
            "jadeite" => Ok(Commodity::Jadeite),
            "lepidolite" => Ok(Commodity::Lepidolite),
            "lithiumhydroxide" => Ok(Commodity::LithiumHydroxide),
            "lowtemperaturediamond" => Ok(Commodity::LowTemperatureDiamonds),
            "methaneclathrate" => Ok(Commodity::MethaneClathrate),
            "methanolmonohydratecrystals" => Ok(Commodity::MethanolMonohydrateCrystals),
            "moissanite" => Ok(Commodity::Moissanite),
            "monazite" => Ok(Commodity::Monazite),
            "musgravite" => Ok(Commodity::Musgravite),
            "painite" => Ok(Commodity::Painite),
            "pyrophyllite" => Ok(Commodity::Pyrophyllite),
            "rhodplumsite" => Ok(Commodity::Rhodplumsite),
            "rutile" => Ok(Commodity::Rutile),
            "serendibite" => Ok(Commodity::Serendibite),
            "taaffeite" => Ok(Commodity::Taaffeite),
            "uraninite" => Ok(Commodity::Uraninite),
            "opal" => Ok(Commodity::VoidOpal),
            "airelics" => Ok(Commodity::AIRelics),
            "ancientartefact" => Ok(Commodity::AncientArtefact),
            "ancientkey" => Ok(Commodity::AncientKey),
            "anomalyparticles" => Ok(Commodity::AnomalyParticles),
            "antimattercontainmentunit" => Ok(Commodity::AntimatterContainmentUnit),
            "aniquejewellery" => Ok(Commodity::AniqueJewellery),
            "antiquities" => Ok(Commodity::Antiquities),
            "assaultplans" => Ok(Commodity::AssaultPlans),
            "blackbox" => Ok(Commodity::BlackBox),
            "bonefragments" => Ok(Commodity::BoneFragments),
            "caustictissuesample" => Ok(Commodity::CausticTissueSample),
            "commercialsamples" => Ok(Commodity::CommercialSamples),
            "coralsap" => Ok(Commodity::CoralSap),
            "cystspecimen" => Ok(Commodity::CystSpecimen),
            "damagedescapepod" => Ok(Commodity::DamagedEscapePod),
            "datacore" => Ok(Commodity::DataCore),
            "diplomaticbag" => Ok(Commodity::DiplomaticBag),
            "earthrelics" => Ok(Commodity::EarthRelics),
            "encryptedcorrespondence" => Ok(Commodity::EncryptedCorrespondence),
            "encrypteddatastorage" => Ok(Commodity::EncryptedDataStorage),
            "experimentalchemicals" => Ok(Commodity::ExperimentalChemicals),
            "fossilremnants" => Ok(Commodity::FossilRemnants),
            "genebank" => Ok(Commodity::GeneBank),
            "geologicalsamples" => Ok(Commodity::GeologicalSamples),
            "ancientcasket" => Ok(Commodity::GuardianCasket),
            "ancientorb" => Ok(Commodity::GuardianOrb),
            "ancientrelic" => Ok(Commodity::GuardianRelic),
            "ancienttablet" => Ok(Commodity::GuardianTablet),
            "ancienttotem" => Ok(Commodity::GuardianTotem),
            "ancienturn" => Ok(Commodity::GuardianUrn),
            "hostages" => Ok(Commodity::Hostages),
            "impurespiremineral" => Ok(Commodity::ImpureSpireMineral),
            "largesurveydatacache" => Ok(Commodity::LargeSurveyDataCache),
            "militaryintelligence" => Ok(Commodity::MilitaryIntelligence),
            "militaryplans" => Ok(Commodity::MilitaryPlans),
            "molluscbraintissue" => Ok(Commodity::MolluscBrainTissue),
            "molluscfluid" => Ok(Commodity::MolluscFluid),
            "molluscmembrane" => Ok(Commodity::MolluscMembrane),
            "molluscmycelium" => Ok(Commodity::MolluscMycelium),
            "molluscsofttissue" => Ok(Commodity::MolluscSoftTissue),
            "molluscspores" => Ok(Commodity::MolluscSpores),
            "mysteriousidol" => Ok(Commodity::MysteriousIdol),
            "occupiedcryopod" => Ok(Commodity::OccupiedEscapePod),
            "organsample" => Ok(Commodity::OrganSample),
            "personaleffects" => Ok(Commodity::PersonalEffects),
            "podcoretissue" => Ok(Commodity::PodCoreTissue),
            "poddeadtissue" => Ok(Commodity::PodDeadTissue),
            "podmesoglea" => Ok(Commodity::PodMesoglea),
            "podoutertissue" => Ok(Commodity::PodOuterTissue),
            "podshelltissue" => Ok(Commodity::PodShellTissue),
            "podsurfacetissue" => Ok(Commodity::PodSurfaceTissue),
            "podtissue" => Ok(Commodity::PodTissue),
            "politicalprisoners" => Ok(Commodity::PoliticalPrisoners),
            "preciousgems" => Ok(Commodity::PreciousGems),
            "prohibitedresearchmaterials" => Ok(Commodity::ProhibitedResearchMaterials),
            "protectivemembranescrap" => Ok(Commodity::ProtectiveMembraneScrap),
            "prototypetech" => Ok(Commodity::PrototypeTech),
            "rareartwork" => Ok(Commodity::RareArtwork),
            "rebeltransmission" => Ok(Commodity::RebelTransmission),
            "sap8corecontainer" => Ok(Commodity::SAP8CoreContainer),
            "scientificresearch" => Ok(Commodity::ScientificResearch),
            "scientificsamples" => Ok(Commodity::ScientificSamples),
            "semirefinesspiremineral" => Ok(Commodity::SemiRefinesSpireMineral),
            "smallsurveydatacache" => Ok(Commodity::SmallSurveyDataCache),
            "spacepioneerrelics" => Ok(Commodity::SpacePioneerRelics),
            "tacticaldata" => Ok(Commodity::TacticalData),
            "technicalblueprints" => Ok(Commodity::TechnicalBlueprints),
            "thargoidbasilisktissuesample" => Ok(Commodity::ThargoidBasiliskTissueSample),
            "thargoidbiostoragecapsule" => Ok(Commodity::ThargoidBioStorageCapsule),
            "thargoidbiologicalmatter" => Ok(Commodity::ThargoidBiologicalMatter),
            "thargoidcyclopstissuesample" => Ok(Commodity::ThargoidCyclopsTissueSample),
            "thargoidglaivetissuesample" => Ok(Commodity::ThargoidGlaiveTissueSample),
            "thargoidheart" => Ok(Commodity::ThargoidHeart),
            "thargoidhydratissuesample" => Ok(Commodity::ThargoidHydraTissueSample),
            "thargoidlink" => Ok(Commodity::ThargoidLink),
            "thargoidmedusatissuesample" => Ok(Commodity::ThargoidMedusaTissueSample),
            "thargoidorthrustissuesample" => Ok(Commodity::ThargoidOrthrusTissueSample),
            "thargoidprobe" => Ok(Commodity::ThargoidProbe),
            "thargoidresin" => Ok(Commodity::ThargoidResin),
            "thargoidscouttissuesample" => Ok(Commodity::ThargoidScoutTissueSample),
            "thargoidscythetissuesample" => Ok(Commodity::ThargoidScytheTissueSample),
            "thargoidgeneratortissuesample" => Ok(Commodity::ThargoidGeneratorTissueSample),
            "thargoidsensor" => Ok(Commodity::ThargoidSensor),
            "thargoidtechnologysamples" => Ok(Commodity::ThargoidTechnologySamples),
            "timecapsule" => Ok(Commodity::TimeCapsule),
            "titandeeptissuesample" => Ok(Commodity::TitanDeepTissueSample),
            "titandrivecomponent" => Ok(Commodity::TitanDriveComponent),
            "titanmawdeeptissuesample" => Ok(Commodity::TitanMawDeepTissueSample),
            "titanmawpartialtissuesample" => Ok(Commodity::TitanMawPartialTissueSample),
            "titanmawtissuesample" => Ok(Commodity::TitanMawTissueSample),
            "titanpartialtissuesample" => Ok(Commodity::TitanPartialTissueSample),
            "titantissuesample" => Ok(Commodity::TitanTissueSample),
            "tradedata" => Ok(Commodity::TradeData),
            "trinketsofhiddenfortune" => Ok(Commodity::TrinketsOfHiddenFortune),
            "unclassifiedrelic" => Ok(Commodity::UnclassifiedRelic),
            "unoccupiedescapepod" => Ok(Commodity::UnoccupiedEscapePod),
            "unstabledatacore" => Ok(Commodity::UnstableDataCore),
            "wreckagecomponents" => Ok(Commodity::WreckageComponents),
            "imperialslaves" => Ok(Commodity::ImperialSlaves),
            "slaves" => Ok(Commodity::Slaves),
            "advancedcatalysers" => Ok(Commodity::AdvancedCatalysers),
            "animalmonitors" => Ok(Commodity::AnimalMonitors),
            "aquaponicsystems" => Ok(Commodity::AquaponicSystems),
            "autofabricators" => Ok(Commodity::AutoFabricators),
            "bioreducinglichen" => Ok(Commodity::BioreducingLichen),
            "computercomponents" => Ok(Commodity::ComputerComponents),
            "hazardousenvironmentsuits" => Ok(Commodity::HESuits),
            "diagnosticsensor" => Ok(Commodity::HardwareDiagnosticSensor),
            "landenrichmentsystems" => Ok(Commodity::LandEnrichmentSystems),
            "medialdiagnosticequipment" => Ok(Commodity::MedialDiagnosticEquipment),
            "microcontrollers" => Ok(Commodity::MicroControllers),
            "muonimager" => Ok(Commodity::MuonImager),
            "nanobreakers" => Ok(Commodity::Nanobreakers),
            "resonatingseparators" => Ok(Commodity::ResonatingSeparators),
            "robotics" => Ok(Commodity::Robotics),
            "structuralregulators" => Ok(Commodity::StructuralRegulators),
            "telemetrysuite" => Ok(Commodity::TelemetrySuite),
            "conductivefabrics" => Ok(Commodity::ConductiveFabrics),
            "leather" => Ok(Commodity::Leather),
            "militarygradefabrics" => Ok(Commodity::MilitaryGradeFabrics),
            "naturalfabrics" => Ok(Commodity::NaturalFabrics),
            "syntheticfabrics" => Ok(Commodity::SyntheticFabrics),
            "biowaste" => Ok(Commodity::Biowaste),
            "chemicalwaste" => Ok(Commodity::ChemicalWaste),
            "scrap" => Ok(Commodity::Scrap),
            "toxicwaste" => Ok(Commodity::ToxicWaste),
            "battleweapons" => Ok(Commodity::BattleWeapons),
            "landmines" => Ok(Commodity::Landmines),
            "nonlethalweapons" => Ok(Commodity::NonLethalWeapons),
            "personalweapons" => Ok(Commodity::PersonalWeapons),
            "reactivearmour" => Ok(Commodity::ReactiveArmour),
            "jaquesquinentianstill" => Ok(Commodity::JaquesQuinentianStill),
            "kinagoviolins" => Ok(Commodity::KinagoViolins),
            "apavietii" => Ok(Commodity::ApaVietii),
            "geawendancedust" => Ok(Commodity::GeawenDanceDust),
            "vanayequiceratomorphafur" => Ok(Commodity::VanayequiCeratomorphaFur),
            "karetiicouture" => Ok(Commodity::KaretiiCouture),
            "mukusubiichitinos" => Ok(Commodity::MukusubiiChitinos),
            "ultracompactprocessorprototypes" => Ok(Commodity::UltraCompactProcessorPrototypes),
            "eleuthermals" => Ok(Commodity::EleuThermals),
            "kamorinhistoricweapons" => Ok(Commodity::KamorinHistoricWeapons),
            "ceremonialheiketea" => Ok(Commodity::CeremonialHeikeTea),
            "vidavantianlace" => Ok(Commodity::VidavantianLace),
            "kachiriginfilterleeches" => Ok(Commodity::KachiriginFilterLeeches),
            "lyraeweed" => Ok(Commodity::LyraeWeed),
            "galactictravelguide" => Ok(Commodity::GalacticTravelGuide),
            "harmasilversearum" => Ok(Commodity::HarmaSilverSeaRum),
            "ngadandarifireopals" => Ok(Commodity::NgadandariFireOpals),
            "alyabodysoap" => Ok(Commodity::AlyaBodySoap),
            "helvetitjpearls" => Ok(Commodity::HelvetitjPearls),
            "ochoengchillies" => Ok(Commodity::OchoengChillies),
            "onionheadbetastrain" => Ok(Commodity::OnionheadBetaStrain),
            "kamitracigars" => Ok(Commodity::KamitraCigars),
            "njangarisaddles" => Ok(Commodity::NjangariSaddles),
            "hiporganophosphates" => Ok(Commodity::HipOrganophosphates),
            "gilyasignatureweapons" => Ok(Commodity::GilyaSignatureWeapons),
            "hr7221wheat" => Ok(Commodity::HR7221Wheat),
            "wheemetewheatcakes" => Ok(Commodity::WheemeteWheatCakes),
            "rajukrumultistoves" => Ok(Commodity::RajukruMultiStoves),
            "nanomedicines" => Ok(Commodity::Nanomedicines),
            "noneuclidianexotanks" => Ok(Commodity::NonEuclidianExotanks),
            "ngunamodernantiques" => Ok(Commodity::NgunaModernAntiques),
            "xihebiomorphiccompanions" => Ok(Commodity::XiheBiomorphicCompanions),
            "esusekucaviar" => Ok(Commodity::EsusekuCaviar),
            "orrerianviciousbrew" => Ok(Commodity::OrrerianViciousBrew),
            "vherculisbodyrub" => Ok(Commodity::VHerculisBodyRub),
            "voidextractcoffee" => Ok(Commodity::VoidExtractCoffee),
            "uszaiantreegrub" => Ok(Commodity::UszaianTreeGrub),
            "haidenblackbrew" => Ok(Commodity::HaidenBlackBrew),
            "motronaexperiencejelly" => Ok(Commodity::MotronaExperienceJelly),
            "jaradharrepuzzlebox" => Ok(Commodity::JaradharrePuzzleBox),
            "personalgifts" => Ok(Commodity::PersonalGifts),
            "mulachigiantfungus" => Ok(Commodity::MulachiGiantFungus),
            "ltthypersweet" => Ok(Commodity::LTTHyperSweet),
            "medbstarlube" => Ok(Commodity::MedbStarlube),
            "giantverrix" => Ok(Commodity::GiantVerrix),
            "hip118311swarm" => Ok(Commodity::HIP118311Swarm),
            "disomacorn" => Ok(Commodity::DisoMaCorn),
            "lavianbrandy" => Ok(Commodity::LavianBrandy),
            "azuremilk" => Ok(Commodity::AzureMilk),
            "leestianeviljuice" => Ok(Commodity::LeestianEvilJuice),
            "coquimspongiformvictuals" => Ok(Commodity::CoquimSpongiformVictuals),
            "leatheryeggs" => Ok(Commodity::LeatheryEggs),
            "shanscharisorchid" => Ok(Commodity::ShansCharisOrchid),
            "konggaale" => Ok(Commodity::KonggaAle),
            "vegaslimweed" => Ok(Commodity::VegaSlimweed),
            "tiolcewaste2pasteunits" => Ok(Commodity::TiolceWaste2PasteUnits),
            "ophiuchexinoartefacts" => Ok(Commodity::OphiuchExinoArtefacts),
            "altairianskin" => Ok(Commodity::AltairianSkin),
            "aganipperush" => Ok(Commodity::AganippeRush),
            "cd75kittenbrandcoffee" => Ok(Commodity::CD75KittenBrandCoffee),
            "havasupaidreamcatcher" => Ok(Commodity::HavasupaiDreamCatcher),
            "eraninpearlwhisky" => Ok(Commodity::EraninPearlWhisky),
            "pavoniseargrubs" => Ok(Commodity::PavonisEarGrubs),
            "onionheadalphastrain" => Ok(Commodity::OnionheadAlphaStrain),
            "indibourbon" => Ok(Commodity::IndiBourbon),
            "bakedgreebles" => Ok(Commodity::BakedGreebles),
            "karsukilocusts" => Ok(Commodity::KarsukiLocusts),
            "masterchefs" => Ok(Commodity::MasterChefs),
            "yasokondileaf" => Ok(Commodity::YasoKondiLeaf),
            "burnhambiledistillate" => Ok(Commodity::BurnhamBileDistillate),
            "thehuttonmug" => Ok(Commodity::TheHuttonMug),
            "centaurimegagin" => Ok(Commodity::CentauriMegaGin),
            "utgaroarmillennialeggs" => Ok(Commodity::UtgaroarMillennialEggs),
            "soontillrelics" => Ok(Commodity::SoontillRelics),
            "zeesszeantgrubglue" => Ok(Commodity::ZeesszeAntGrubGlue),
            "thewatersofshintara" => Ok(Commodity::TheWatersOfShintara),
            "baltahsinevacuumkrill" => Ok(Commodity::BaltahsineVacuumKrill),
            "sanumadecorativemeat" => Ok(Commodity::SanumaDecorativeMeat),
            "giantirukamasnails" => Ok(Commodity::GiantIrukamaSnails),
            "anduligafireworks" => Ok(Commodity::AnduligaFireWorks),
            "crystallinespheres" => Ok(Commodity::CrystallineSpheres),
            "pantaaprayersticks" => Ok(Commodity::PantaaPrayerSticks),
            "chieridanimarinepaste" => Ok(Commodity::ChiEridaniMarinePaste),
            "ethgrezeteabuds" => Ok(Commodity::EthgrezeTeaBuds),
            "deltaphoenicispalms" => Ok(Commodity::DeltaPhoenicisPalms),
            "tarachspice" => Ok(Commodity::TarachSpice),
            "wulpahyperboresystems" => Ok(Commodity::WulpaHyperboreSystems),
            "livehecateseaworms" => Ok(Commodity::LiveHecateSeaWorms),
            "korokungpellets" => Ok(Commodity::KoroKungPellets),
            "bastsnakegin" => Ok(Commodity::BastSnakeGin),
            "terramaterbloodbores" => Ok(Commodity::TerraMaterBloodBores),
            "wuthielokufroth" => Ok(Commodity::WuthieloKuFroth),
            "honestypills" => Ok(Commodity::HonestyPills),
            "cromsilverfesh" => Ok(Commodity::CromSilverFesh),
            "borasetanipathogenetics" => Ok(Commodity::BorasetaniPathogenetics),
            "cetirabbits" => Ok(Commodity::CetiRabbits),
            "aepyornisegg" => Ok(Commodity::AepyornisEgg),
            "uzumokulowgwings" => Ok(Commodity::UzumokuLowGWings),
            "cherbonesbloodcrystals" => Ok(Commodity::CherbonesBloodCrystals),
            "toxandjivirocide" => Ok(Commodity::ToxandjiVirocide),
            "onionhead" => Ok(Commodity::Onionhead),
            "lucanonionhead" => Ok(Commodity::LucanOnionhead),
            "tanmarktranquiltea" => Ok(Commodity::TanmarkTranquilTea),
            "thrutiscream" => Ok(Commodity::ThrutisCream),
            "alacarakmoskinart" => Ok(Commodity::AlacarakmoSkinArt),
            "platinumalloy" => Ok(Commodity::PlatinumAlloy),
            "mokojingbeastfeast" => Ok(Commodity::MokojingBeastFeast),
            "edenapplesofaerial" => Ok(Commodity::EdenApplesOfAerial),
            "chameleoncloth" => Ok(Commodity::ChameleonCloth),
            "taurichimes" => Ok(Commodity::TauriChimes),
            "rusanioldsmokey" => Ok(Commodity::RusaniOldSmokey),
            "azcancriformula42" => Ok(Commodity::AZCancriFormula42),
            "gomanyauponcoffee" => Ok(Commodity::GomanYauponCoffee),
            "gerasiangueuzebeer" => Ok(Commodity::GerasianGueuzeBeer),
            "jarouarice" => Ok(Commodity::JarouaRice),
            "anynacoffee" => Ok(Commodity::AnyNaCoffee),
            "fujintea" => Ok(Commodity::FujinTea),
            "hip10175bushmeat" => Ok(Commodity::HIP10175BushMeat),
            "momusbogspaniel" => Ok(Commodity::MomusBogSpaniel),
            "witchhaulkobebeef" => Ok(Commodity::WitchhaulKobeBeef),
            "saxonwine" => Ok(Commodity::SaxonWine),
            "aroucaconventualsweets" => Ok(Commodity::AroucaConventualSweets),
            "albinoquechuamammothmeat" => Ok(Commodity::AlbinoQuechuaMammothMeat),
            "duradrives" => Ok(Commodity::Duradrives),
            "holvaduellingblades" => Ok(Commodity::HolvaDuellingBlades),
            "rapabaosnakeskins" => Ok(Commodity::RapaBaoSnakeSkins),
            "wolffesh" => Ok(Commodity::WolfFesh),
            "eshuumbrellas" => Ok(Commodity::EshuUmbrellas),
            "neritusberries" => Ok(Commodity::NeritusBerries),
            "jotunmookah" => Ok(Commodity::JotunMookah),
            "chateaudeaegaeon" => Ok(Commodity::ChateauDeAegaeon),
            "belalansrayleather" => Ok(Commodity::BelalansRayLeather),
            "damnacarapaces" => Ok(Commodity::DamnaCarapaces),
            "hipprotosquid" => Ok(Commodity::HIPProtoSquid),
            "mechucoshightea" => Ok(Commodity::MechucosHighTea),
            "deuringastruffles" => Ok(Commodity::DeuringasTruffles),
            "bankiamphibiousleather" => Ok(Commodity::BankiAmphibiousLeather),
            "sothiscrystallinegold" => Ok(Commodity::SothisCrystallineGold),
            "tiegfriessynthsilk" => Ok(Commodity::TiegfriesSynthSilk),
            "volkhabbeedrones" => Ok(Commodity::VolkhabBeeDrones),
            "buckyballbeermats" => Ok(Commodity::BuckyballBeerMats),
            "classifiedexperimentalequipment" => Ok(Commodity::ClassifiedExperimentalEquipment),
            "drones" => Ok(Commodity::Limpet),

            #[cfg(not(feature = "strict"))]
            _ => Ok(Commodity::Unknown(name.to_string())),

            #[cfg(feature = "strict")]
            _ => Err(CommodityError::UnknownCommodity(name.to_string())),
        }
    }
}

lazy_static! {
    static ref COMMODITY_NAME_REGEX: Regex =
        Regex::new(r#"^\$?(USSCargo)?([a-zA-Z_]+?)(_[nN]ame;)?$"#).unwrap();
}

impl FromStr for Commodity {
    type Err = CommodityError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let Some(captures) = COMMODITY_NAME_REGEX.captures(s) else {
            return Err(CommodityError::UnknownCommodity(s.to_string()));
        };

        Commodity::name_to_commodity(
            captures
                .get(2)
                .expect("Should have been captured already")
                .as_str(),
        )
    }
}

from_str_deserialize_impl!(Commodity);

impl Display for Commodity {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                // Chemicals
                Commodity::ArgonomicTreatment => "Argonomic Treatment",
                Commodity::Explosives => "Explosives",
                Commodity::HydrogenFuel => "Hydrogen Fuel",
                Commodity::HydrogenPeroxide => "Hydrogen Peroxide",
                Commodity::LiquidOxygen => "Liquid Oxygen",
                Commodity::MineralOil => "Mineral Oil",
                Commodity::NerveAgents => "Nerve Agents",
                Commodity::Pesticides => "Pesticides",
                Commodity::RockforthFertiliser => "Rockforth Fertiliser",
                Commodity::SurfaceStabilisers => "Surface Stabilisers",
                Commodity::SyntheticReagents => "Synthetic Reagents",
                Commodity::Tritium => "Tritium",
                Commodity::Water => "Water",

                // Consumer items
                Commodity::Clothing => "Clothing",
                Commodity::ConsumerTechnology => "Consumer Technology",
                Commodity::DomesticAppliances => "Domestic Appliances",
                Commodity::EvacuationShelter => "Evacuation Shelter",
                Commodity::SurvivalEquipment => "Survival Equipment",

                // Legal drugs
                Commodity::Beer => "Beer",
                Commodity::BootlegLiquor => "Bootleg Liquor",
                Commodity::Liquor => "Liquor",
                Commodity::Narcotics => "Narcotics",
                Commodity::OnionheadGammaStrain => "Onionhead Gamma Strain",
                Commodity::Tobacco => "Tobacco",
                Commodity::Wine => "Wine",

                // Foods
                Commodity::Algae => "Algae",
                Commodity::AnimalMeat => "Animal Meat",
                Commodity::Coffee => "Coffee",
                Commodity::Fish => "Fish",
                Commodity::FoodCartridges => "Food Cartridges",
                Commodity::FruitAndVegetables => "Fruit and Vegetables",
                Commodity::Grain => "Grain",
                Commodity::SyntheticMeat => "Synthetic Meat",
                Commodity::Tea => "Tea",

                // Industrial materials
                Commodity::CeramicComposites => "Ceramic Composites",
                Commodity::CMMComposite => "CMM Composite",
                Commodity::InsulatingMembrane => "Insulating Membrane",
                Commodity::MetaAlloys => "Meta-Alloys",
                Commodity::MicroWeaveCoolingHoses => "Micro-Weave Cooling Hoses",
                Commodity::NeofabricInsulation => "Neofabric Insulation",
                Commodity::Polymers => "Polymers",
                Commodity::Semiconductors => "Semiconductors",
                Commodity::Superconductors => "Superconductors",

                // Machinery
                Commodity::ArticulationMotors => "Articulation Motors",
                Commodity::AtmosphericProcessors => "Atmospheric Processors",
                Commodity::BuildingFabricators => "Building Fabricators",
                Commodity::CropHarvesters => "Crop Harvesters",
                Commodity::EmergencyPowerCells => "Emergency Power Cells",
                Commodity::EnergyGridAssembly => "Energy Grid Assembly",
                Commodity::ExhaustManifold => "Exhaust Manifold",
                Commodity::GeologicalEquipment => "Geological Equipment",
                Commodity::HeatsinkInterlink => "Heatsink Interlink",
                Commodity::HNShockMount => "HN Shock Mount",
                Commodity::IonDistributor => "Ion Distributor",
                Commodity::MagneticEmitterCoil => "Magnetic Emitter Coil",
                Commodity::MarineEquipment => "Marine Equipment",
                Commodity::MicrobialFurnaces => "Microbial Furnaces",
                Commodity::MineralExtractors => "Mineral Extractors",
                Commodity::ModularTerminals => "Modular Terminals",
                Commodity::PowerConverter => "Power Converter",
                Commodity::PowerGenerators => "Power Generators",
                Commodity::PowerTransferBus => "Power TransferBus",
                Commodity::RadiationBaffle => "Radiation Baffle",
                Commodity::ReinforcedMountingPlate => "Reinforced Mounting Plate",
                Commodity::SkimmerComponents => "Skimmer Components",
                Commodity::ThermalCoolingUnits => "Thermal Cooling Units",
                Commodity::WaterPurifiers => "Water Purifiers",

                // Medicines
                Commodity::AdvancedMedicines => "Advanced Medicines",
                Commodity::AgriMedicines => "Agri-Medicines",
                Commodity::BasicMedicines => "Basic Medicines",
                Commodity::CombatStabilisers => "Combat Stabilisers",
                Commodity::PerformanceEnhancers => "Performance Enhancers",
                Commodity::ProgenitorCells => "Progenitor Cells",

                // Metals
                Commodity::Aluminium => "Aluminium",
                Commodity::Beryllium => "Beryllium",
                Commodity::Bismuth => "Bismuth",
                Commodity::Cobalt => "Cobalt",
                Commodity::Copper => "Copper",
                Commodity::Gallium => "Gallium",
                Commodity::Gold => "Gold",
                Commodity::Hafnium178 => "Hafnium 178",
                Commodity::Indium => "Indium",
                Commodity::Lanthanum => "Lanthanum",
                Commodity::Lithium => "Lithium",
                Commodity::Osmium => "Osmium",
                Commodity::Palladium => "Palladium",
                Commodity::Platinum => "Platinum",
                Commodity::Praseodymium => "Praseodymium",
                Commodity::Samarium => "Samarium",
                Commodity::Silver => "Silver",
                Commodity::Tantalum => "Tantalum",
                Commodity::Thallium => "Thallium",
                Commodity::Thorium => "Thorium",
                Commodity::Titanium => "Titanium",
                Commodity::Uranium => "Uranium",

                // Minerals
                Commodity::Alexandrite => "Alexandrite",
                Commodity::Bauxite => "Bauxite",
                Commodity::Benitoite => "Benitoite",
                Commodity::Bertrandite => "Bertrandite",
                Commodity::Bromellite => "Bromellite",
                Commodity::Coltan => "Coltan",
                Commodity::Cryolite => "Cryolite",
                Commodity::Gallite => "Gallite",
                Commodity::Goslarite => "Goslarite",
                Commodity::Grandidierite => "Grandidierite",
                Commodity::Indite => "Indite",
                Commodity::Jadeite => "Jadeite",
                Commodity::Lepidolite => "Lepidolite",
                Commodity::LithiumHydroxide => "Lithium Hydroxide",
                Commodity::LowTemperatureDiamonds => "Low Temperature Diamonds",
                Commodity::MethaneClathrate => "Methane Clathrate",
                Commodity::MethanolMonohydrateCrystals => "Methanol Monohydrate Crystals",
                Commodity::Moissanite => "Moissanite",
                Commodity::Monazite => "Monazite",
                Commodity::Musgravite => "Musgravite",
                Commodity::Painite => "Painite",
                Commodity::Pyrophyllite => "Pyrophyllite",
                Commodity::Rhodplumsite => "Rhodplumsite",
                Commodity::Rutile => "Rutile",
                Commodity::Serendibite => "Serendibite",
                Commodity::Taaffeite => "Taaffeite",
                Commodity::Uraninite => "Uraninite",
                Commodity::VoidOpal => "VoidOpal",

                // Salvage
                Commodity::AIRelics => "AI Relics",
                Commodity::AncientArtefact => "Ancient Artefact",
                Commodity::AncientKey => "Ancient Key",
                Commodity::AnomalyParticles => "Anomaly Particles",
                Commodity::AntimatterContainmentUnit => "Antimatter Containment Unit",
                Commodity::AniqueJewellery => "Anique Jewellery",
                Commodity::Antiquities => "Antiquities",
                Commodity::AssaultPlans => "Assault Plans",
                Commodity::BlackBox => "Black Box",
                Commodity::BoneFragments => "Bone Fragments",
                Commodity::CausticTissueSample => "Caustic Tissue Sample",
                Commodity::CommercialSamples => "Commercial Samples",
                Commodity::CoralSap => "Coral Sap",
                Commodity::CystSpecimen => "Cyst Specimen",
                Commodity::DamagedEscapePod => "Damaged Escape Pod",
                Commodity::DataCore => "Data Core",
                Commodity::DiplomaticBag => "Diplomatic Bag",
                Commodity::EarthRelics => "Earth Relics",
                Commodity::EncryptedCorrespondence => "Encrypted Correspondence",
                Commodity::EncryptedDataStorage => "Encrypted Data Storage",
                Commodity::ExperimentalChemicals => "Experimental Chemicals",
                Commodity::FossilRemnants => "Fossil Remnants",
                Commodity::GeneBank => "Gene Bank",
                Commodity::GeologicalSamples => "Geological Samples",
                Commodity::GuardianCasket => "Guardian Casket",
                Commodity::GuardianOrb => "Guardian Orb",
                Commodity::GuardianRelic => "Guardian Relic",
                Commodity::GuardianTablet => "Guardian Tablet",
                Commodity::GuardianTotem => "Guardian Totem",
                Commodity::GuardianUrn => "Guardian Urn",
                Commodity::Hostages => "Hostages",
                Commodity::ImpureSpireMineral => "Impure Spire Mineral",
                Commodity::LargeSurveyDataCache => "Large Survey Data Cache",
                Commodity::MilitaryIntelligence => "Military Intelligence",
                Commodity::MilitaryPlans => "Military Plans",
                Commodity::MolluscBrainTissue => "Mollusc Brain Tissue",
                Commodity::MolluscFluid => "Mollusc Fluid",
                Commodity::MolluscMembrane => "Mollusc Membrane",
                Commodity::MolluscMycelium => "Mollusc Mycelium",
                Commodity::MolluscSoftTissue => "Mollusc Soft Tissue",
                Commodity::MolluscSpores => "Mollusc Spores",
                Commodity::MysteriousIdol => "Mysterious Idol",
                Commodity::OccupiedEscapePod => "Occupied Escape Pod",
                Commodity::OrganSample => "Organ Sample",
                Commodity::PersonalEffects => "Personal Effects",
                Commodity::PodCoreTissue => "Pod Core Tissue",
                Commodity::PodDeadTissue => "Pod Dead Tissue",
                Commodity::PodMesoglea => "Pod Mesoglea",
                Commodity::PodOuterTissue => "Pod Outer Tissue",
                Commodity::PodShellTissue => "Pod Shell Tissue",
                Commodity::PodSurfaceTissue => "Pod Surface Tissue",
                Commodity::PodTissue => "Pod Tissue",
                Commodity::PoliticalPrisoners => "Political Prisoners",
                Commodity::PreciousGems => "Precious Gems",
                Commodity::ProhibitedResearchMaterials => "Prohibited Research Materials",
                Commodity::ProtectiveMembraneScrap => "Protective MembraneScrap",
                Commodity::PrototypeTech => "Prototype Tech",
                Commodity::RareArtwork => "Rare Artwork",
                Commodity::RebelTransmission => "Rebel Transmission",
                Commodity::SAP8CoreContainer => "SAP 8 Core Container",
                Commodity::ScientificResearch => "Scientific Research",
                Commodity::ScientificSamples => "Scientific Samples",
                Commodity::SemiRefinesSpireMineral => "Semi Refines Spire Mineral",
                Commodity::SmallSurveyDataCache => "Small Survey Data Cache",
                Commodity::SpacePioneerRelics => "Space Pioneer Relics",
                Commodity::TacticalData => "Tactical Data",
                Commodity::TechnicalBlueprints => "Technical Blueprints",
                Commodity::ThargoidBasiliskTissueSample => "Thargoid Basilisk Tissue Sample",
                Commodity::ThargoidBioStorageCapsule => "Thargoid Bio Storage Capsule",
                Commodity::ThargoidBiologicalMatter => "Thargoid Biological Matter",
                Commodity::ThargoidCyclopsTissueSample => "Thargoid Cyclops Tissue Sample",
                Commodity::ThargoidGlaiveTissueSample => "Thargoid Glaive Tissue Sample",
                Commodity::ThargoidHeart => "Thargoid Heart",
                Commodity::ThargoidHydraTissueSample => "Thargoid Hydra Tissue Sample",
                Commodity::ThargoidLink => "Thargoid Link",
                Commodity::ThargoidMedusaTissueSample => "Thargoid Medusa Tissue Sample",
                Commodity::ThargoidOrthrusTissueSample => "Thargoid Orthrus Tissue Sample",
                Commodity::ThargoidProbe => "Thargoid Probe",
                Commodity::ThargoidResin => "Thargoid Resin",
                Commodity::ThargoidScoutTissueSample => "Thargoid Scout Tissue Sample",
                Commodity::ThargoidScytheTissueSample => "Thargoid Scythe Tissue Sample",
                Commodity::ThargoidGeneratorTissueSample => "Thargoid Generator Tissue Sample",
                Commodity::ThargoidSensor => "Thargoid Sensor",
                Commodity::ThargoidTechnologySamples => "Thargoid Technology Samples",
                Commodity::TimeCapsule => "Time Capsule",
                Commodity::TitanDeepTissueSample => "Titan Deep Tissue Sample",
                Commodity::TitanDriveComponent => "Titan Drive Component",
                Commodity::TitanMawDeepTissueSample => "Titan Maw Deep Tissue Sample",
                Commodity::TitanMawPartialTissueSample => "Titan Maw Partial Tissue Sample",
                Commodity::TitanMawTissueSample => "Titan Maw Tissue Sample",
                Commodity::TitanPartialTissueSample => "Titan Partial Tissue Sample",
                Commodity::TitanTissueSample => "Titan Tissue Sample",
                Commodity::TradeData => "Trade Data",
                Commodity::TrinketsOfHiddenFortune => "Trinkets Of Hidden Fortune",
                Commodity::UnclassifiedRelic => "Unclassified Relic",
                Commodity::UnoccupiedEscapePod => "Unoccupied EscapePod",
                Commodity::UnstableDataCore => "Unstable Data Core",
                Commodity::WreckageComponents => "Wreckage Components",

                // Slaves
                Commodity::ImperialSlaves => "Imperial Slaves",
                Commodity::Slaves => "Slaves",

                // Technology
                Commodity::AdvancedCatalysers => "Advanced Catalysers",
                Commodity::AnimalMonitors => "Animal Monitors",
                Commodity::AquaponicSystems => "Aquaponic Systems",
                Commodity::AutoFabricators => "Auto Fabricators",
                Commodity::BioreducingLichen => "Bioreducing Lichen",
                Commodity::ComputerComponents => "Computer Components",
                Commodity::HESuits => "H.E. Suits",
                Commodity::HardwareDiagnosticSensor => "Hardware Diagnostic Sensor",
                Commodity::LandEnrichmentSystems => "Land Enrichment Systems",
                Commodity::MedialDiagnosticEquipment => "Medial Diagnostic Equipment",
                Commodity::MicroControllers => "Micro Controllers",
                Commodity::MuonImager => "Muon Imager",
                Commodity::Nanobreakers => "Nanobreakers",
                Commodity::ResonatingSeparators => "Resonating Separators",
                Commodity::Robotics => "Robotics",
                Commodity::StructuralRegulators => "Structural Regulators",
                Commodity::TelemetrySuite => "Telemetry Suite",

                // Textiles
                Commodity::ConductiveFabrics => "Conductive Fabrics",
                Commodity::Leather => "Leather",
                Commodity::MilitaryGradeFabrics => "Military Grade Fabrics",
                Commodity::NaturalFabrics => "Natural Fabrics",
                Commodity::SyntheticFabrics => "Synthetic Fabrics",

                // Waste
                Commodity::Biowaste => "Biowaste",
                Commodity::ChemicalWaste => "Chemical Waste",
                Commodity::Scrap => "Scrap",
                Commodity::ToxicWaste => "Toxic Waste",

                // Weapons
                Commodity::BattleWeapons => "Battle Weapons",
                Commodity::Landmines => "Landmines",
                Commodity::NonLethalWeapons => "Non-Lethal Weapons",
                Commodity::PersonalWeapons => "Personal Weapons",
                Commodity::ReactiveArmour => "Reactive Armour",

                // Rare
                Commodity::JaquesQuinentianStill => "Jaques Quinentian Still",
                Commodity::KinagoViolins => "Kinago Violins",
                Commodity::ApaVietii => "Apa Vietii",
                Commodity::GeawenDanceDust => "Geawen Dance Dust",
                Commodity::VanayequiCeratomorphaFur => "Vanayequi Ceratomorpha Fur",
                Commodity::KaretiiCouture => "Karetii Couture",
                Commodity::MukusubiiChitinos => "Mukusubii Chitin-os",
                Commodity::UltraCompactProcessorPrototypes => "Ultra-Compact Processor Prototypes",
                Commodity::EleuThermals => "Eleu Thermals",
                Commodity::KamorinHistoricWeapons => "Kamorin Historic Weapons",
                Commodity::CeremonialHeikeTea => "Ceremonial Heike Tea",
                Commodity::VidavantianLace => "Kachirigin Filter Leeches",
                Commodity::KachiriginFilterLeeches => "Vidavantian Lace",
                Commodity::LyraeWeed => "Lyrae Weed",
                Commodity::GalacticTravelGuide => "Harma Silver Sea Rum",
                Commodity::HarmaSilverSeaRum => "Galactic Travel Guide",
                Commodity::NgadandariFireOpals => "Ngadandari Fire Opals",
                Commodity::AlyaBodySoap => "Alya Body Soap",
                Commodity::HelvetitjPearls => "Onionhead Beta Strain",
                Commodity::OchoengChillies => "Ochoeng Chillies",
                Commodity::OnionheadBetaStrain => "Njangari Saddles",
                Commodity::KamitraCigars => "Kamitra Cigars",
                Commodity::NjangariSaddles => "Helvetitj Pearls",
                Commodity::HipOrganophosphates => "Hip Organophosphates",
                Commodity::GilyaSignatureWeapons => "Gilya Signature Weapons",
                Commodity::HR7221Wheat => "HR 7221 Wheat",
                Commodity::WheemeteWheatCakes => "Wheemete Wheat Cakes",
                Commodity::RajukruMultiStoves => "Nanomedicines",
                Commodity::Nanomedicines => "Rajukru Multi-Stoves",
                Commodity::NonEuclidianExotanks => "Non Euclidian Exotanks",
                Commodity::NgunaModernAntiques => "Nguna Modern Antiques",
                Commodity::XiheBiomorphicCompanions => "Xihe Biomorphic Companions",
                Commodity::EsusekuCaviar => "Esuseku Caviar",
                Commodity::OrrerianViciousBrew => "Haiden Black Brew",
                Commodity::VHerculisBodyRub => "Void Extract Coffee",
                Commodity::VoidExtractCoffee => "Personal Gifts",
                Commodity::UszaianTreeGrub => "V Herculis Body Rub",
                Commodity::HaidenBlackBrew => "Orrerian Vicious Brew",
                Commodity::MotronaExperienceJelly => "Uszaian Tree Grub",
                Commodity::JaradharrePuzzleBox => "Jaradharre Puzzle Box",
                Commodity::PersonalGifts => "Motrona Experience Jelly",
                Commodity::MulachiGiantFungus => "LTT Hyper Sweet",
                Commodity::LTTHyperSweet => "HIP 118311 Swarm",
                Commodity::MedbStarlube => "Mulachi Giant Fungus",
                Commodity::GiantVerrix => "Giant Verrix",
                Commodity::HIP118311Swarm => "Medb Starlube",
                Commodity::DisoMaCorn => "Diso Ma Corn",
                Commodity::LavianBrandy => "Lavian Brandy",
                Commodity::AzureMilk => "Coquim Spongiform Victuals",
                Commodity::LeestianEvilJuice => "Azure Milk",
                Commodity::CoquimSpongiformVictuals => "Leestian Evil Juice",
                Commodity::LeatheryEggs => "Kongga Ale",
                Commodity::ShansCharisOrchid => "Shan's Charis Orchid",
                Commodity::KonggaAle => "Leathery Eggs",
                Commodity::VegaSlimweed => "Tiolce Waste2Paste Units",
                Commodity::TiolceWaste2PasteUnits => "Vega Slimweed",
                Commodity::OphiuchExinoArtefacts => "Ophiuch Exino Artefacts",
                Commodity::AltairianSkin => "Altairian Skin",
                Commodity::AganippeRush => "Aganippe Rush",
                Commodity::CD75KittenBrandCoffee => "CD-75 Kitten Brand Coffee",
                Commodity::HavasupaiDreamCatcher => "Havasupai Dream Catcher",
                Commodity::EraninPearlWhisky => "Pavonis Ear Grubs",
                Commodity::PavonisEarGrubs => "Eranin Pearl Whisky",
                Commodity::OnionheadAlphaStrain => "Karsuki Locusts",
                Commodity::IndiBourbon => "Yaso Kondi Leaf",
                Commodity::BakedGreebles => "Indi Bourbon",
                Commodity::KarsukiLocusts => "Onionhead Alpha Strain",
                Commodity::MasterChefs => "Master Chefs",
                Commodity::YasoKondiLeaf => "Baked Greebles",
                Commodity::BurnhamBileDistillate => "Burnham Bile Distillate",
                Commodity::TheHuttonMug => "Centauri Mega Gin",
                Commodity::CentauriMegaGin => "The Hutton Mug",
                Commodity::UtgaroarMillennialEggs => "Utgaroar Millennial Eggs",
                Commodity::SoontillRelics => "Soontill Relics",
                Commodity::ZeesszeAntGrubGlue => "Zeessze Ant Grub Glue",
                Commodity::TheWatersOfShintara => "Baltah'sine Vacuum Krill",
                Commodity::BaltahsineVacuumKrill => "Giant Irukama Snails",
                Commodity::SanumaDecorativeMeat => "The Waters Of Shintara",
                Commodity::GiantIrukamaSnails => "Crystalline Spheres",
                Commodity::AnduligaFireWorks => "Pantaa Prayer Sticks",
                Commodity::CrystallineSpheres => "Anduliga Fire Works",
                Commodity::PantaaPrayerSticks => "Sanuma Decorative Meat",
                Commodity::ChiEridaniMarinePaste => "Chi Eridani Marine Paste",
                Commodity::EthgrezeTeaBuds => "Delta Phoenicis Palms",
                Commodity::DeltaPhoenicisPalms => "Tarach Spice",
                Commodity::TarachSpice => "Wulpa Hyperbore Systems",
                Commodity::WulpaHyperboreSystems => "Ethgreze Tea Buds",
                Commodity::LiveHecateSeaWorms => "Live Hecate Sea Worms",
                Commodity::KoroKungPellets => "Wuthielo Ku Froth",
                Commodity::BastSnakeGin => "Bast Snake Gin",
                Commodity::TerraMaterBloodBores => "Koro Kung Pellets",
                Commodity::WuthieloKuFroth => "Terra Mater Blood Bores",
                Commodity::HonestyPills => "Ceti Rabbits",
                Commodity::CromSilverFesh => "Aepyornis Egg",
                Commodity::BorasetaniPathogenetics => "Crom Silver Fesh",
                Commodity::CetiRabbits => "Uzumoku Low-G Wings",
                Commodity::AepyornisEgg => "Honesty Pills",
                Commodity::UzumokuLowGWings => "Borasetani Pathogenetics",
                Commodity::CherbonesBloodCrystals => "Toxandji Virocide",
                Commodity::ToxandjiVirocide => "Cherbones Blood Crystals",
                Commodity::Onionhead => "Onionhead",
                Commodity::LucanOnionhead => "Tanmark Tranquil Tea",
                Commodity::TanmarkTranquilTea => "Lucan Onionhead",
                Commodity::ThrutisCream => "Thrutis Cream",
                Commodity::AlacarakmoSkinArt => "Alacarakmo Skin Art",
                Commodity::PlatinumAlloy => "Platinum Alloy",
                Commodity::MokojingBeastFeast => "Eden Apples Of Aerial",
                Commodity::EdenApplesOfAerial => "Mokojing Beast Feast",
                Commodity::ChameleonCloth => "Chameleon Cloth",
                Commodity::TauriChimes => "Tauri Chimes",
                Commodity::RusaniOldSmokey => "Goman Yaupon Coffee",
                Commodity::AZCancriFormula42 => "Rusani Old Smokey",
                Commodity::GomanYauponCoffee => "AZ Cancri Formula 42",
                Commodity::GerasianGueuzeBeer => "Gerasian Gueuze Beer",
                Commodity::JarouaRice => "Jaroua Rice",
                Commodity::AnyNaCoffee => "HIP 10175 Bush Meat",
                Commodity::FujinTea => "Fujin Tea",
                Commodity::HIP10175BushMeat => "Any Na Coffee",
                Commodity::MomusBogSpaniel => "Momus Bog Spaniel",
                Commodity::WitchhaulKobeBeef => "Witchhaul Kobe Beef",
                Commodity::SaxonWine => "Saxon Wine",
                Commodity::AroucaConventualSweets => "Arouca Conventual Sweets",
                Commodity::AlbinoQuechuaMammothMeat => "Albino Quechua Mammoth Meat",
                Commodity::Duradrives => "Holva Duelling Blades",
                Commodity::HolvaDuellingBlades => "Duradrives",
                Commodity::RapaBaoSnakeSkins => "Rapa Bao Snake Skins",
                Commodity::WolfFesh => "Eshu Umbrellas",
                Commodity::EshuUmbrellas => "Wolf Fesh",
                Commodity::NeritusBerries => "Neritus Berries",
                Commodity::JotunMookah => "Jotun Mookah",
                Commodity::ChateauDeAegaeon => "Chateau De Aegaeon",
                Commodity::BelalansRayLeather => "Belalans Ray Leather",
                Commodity::DamnaCarapaces => "Damna Carapaces",
                Commodity::HIPProtoSquid => "HIP Proto-Squid",
                Commodity::MechucosHighTea => "Mechucos High Tea",
                Commodity::DeuringasTruffles => "Deuringas Truffles",
                Commodity::BankiAmphibiousLeather => "Banki Amphibious Leather",
                Commodity::SothisCrystallineGold => "Sothis Crystalline Gold",
                Commodity::TiegfriesSynthSilk => "Tiegfries Synth Silk",
                Commodity::VolkhabBeeDrones => "Volkhab Bee Drones",
                Commodity::BuckyballBeerMats => "Buckyball Beer Mats",
                Commodity::ClassifiedExperimentalEquipment => "Classified Experimental Equipment",
                Commodity::Limpet => "Limpet",

                #[cfg(not(feature = "strict"))]
                Commodity::Unknown(unknown) => unknown,
            }
        )
    }
}
