pub mod codex_entry;
pub mod planetary_signal_type;
pub mod codex_star_class_entry;
pub mod codex_geological_entry;
pub mod codex_anomaly_entry;
pub mod codex_thargoid_entry;
pub mod codex_guardian_entry;
pub mod codex_planet_entry;
pub mod codex_organic_structure_entry;
