name: "Formatting"

on:
  push:
    branches:
      - "master"
      - "ci"
  pull_request:
    branches:
      - "master"
      - "ci"

jobs:
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
